### ISSUE TITLE
Try to include in maven, Missing artifact com.sun.java:tools:jar:1.8.0_20

### ISSUE THREAD

**Issue by fancellu** [OpenHFT/Chronicle-Map#1]
``` xml
 <dependency>
     <groupId>net.openhft</groupId>
     <artifactId>chronicle-map</artifactId>
     <version>1.0.2</version>
   </dependency>
```

Using JDK 1.7

From the 1.8 in the tools, can I assume this requires JDK 1.8?

Thanks?

**Comment by anandchakru** [comment]
for some reason, I'm facing this same problem on `3.13.0` and had to add the `<exclusion>`

**Comment by RobAustin** [comment]
It’s part of the tools.jar in the jdk

**Comment by rahulsolanki-infinity** [comment]
I am running on ubuntu and facing the same issue

**Comment by charj** [comment]
Facing the same issue on ubuntu with intellij
