### ISSUE TITLE
Old fashion all in one distribution please

### ISSUE THREAD

**Issue by haochenx** [OpenHFT/Chronicle-Map#101]
Our Java project still doesn't use a dependency management system (how dare it!!), and it seems that simply downloading the chronicle-map-x.x.x.jar is not enough. Could you please provide a distribution (for example a zip file) with all the runtime dependencies?

**Comment by peter-lawrey** [comment]
Hello,
   We do this for paying customers on an ad hoc basis (as they require)

We would be happy to talk to you about a support contract.

Regards, Peter.

**Comment by haochenx** [comment]
Aha! okay, but we are only using the library for a very minor caching task so I don't think we are going to get a support contract. is there any workaround?

(I really think our project should adopt newer build managers, or at least adopt a dependency manager, but the project leader says no.. to disclose: we are still using ant, and hardcoding the jars to be copied in the build script)

**Comment by peter-lawrey** [comment]
If you are using ant you can use Ivy which downloads dependencies.

**Comment by haochenx** [comment]
I know, but our project leader is even refusing to use Ivy! I try to persuade him at least twice, without any luck.

**Comment by peter-lawrey** [comment]
We could do an all build periodically but no guarantees.

**Comment by haochenx** [comment]
that would be very helpful! although if it's a lot of work for your team, we could just go for another approach: it's not critical for us to use Chronicle Map and the way we plan to use it is probably not the intended way of how the library is designed for
