### ISSUE TITLE
AssertionError - JavacTool - not found when executing app from command line - app using ChronicleMap API

### ISSUE THREAD

**Issue by felixunivers** [OpenHFT/Chronicle-Map#104]
Good day,

my project runs fine under Netbeans IDE.
My POM.XML includes Chronicle map including:

`<artifactId>maven-assembly-plugin</artifactId>

     <configuration> 
        <descriptorRefs> 
            <descriptorRef>jar-with-dependencies</descriptorRef>
        </descriptorRefs>
        .... etc. ... 
        + 
        <dependency> 
           <groupId>net.openhft</groupId>
           <artifactId>chronicle-map</artifactId>
           <version>3.10.2-SNAPSHOT</version>
         </dependency>
`
Compiles fine

However, there is an issue of error at the command level execution. Here is the error:

`
Exception in thread "main" java.lang.AssertionError: java.lang.ClassNotFoundException: com.sun.tools.javac.api.JavacTool at net.openhft.chronicle.values.CompilerUtils.reset(CompilerUtils.java:61) at net.openhft.chronicle.values.CompilerUtils.<clinit>(CompilerUtils.java:50) etc ....
`

Would you please provide a concrete solution (example of POM entries to filter out or add components; or other steps necessary) to be able to run a project using ChronicleMap API from command line:

`java -jar myapp.jar`

Thank you.

**Comment by umeshshende** [comment]
I'm still unable to find the solution any update on this

**Comment by minborg** [comment]
Make sure you have a complete JDK. I am closing this issue. Please reopen if the problem persists in recent versions of Chronicle Map
