### ISSUE TITLE
Add a way to inspect per-segment stats

### ISSUE THREAD

**Issue by leventov** [OpenHFT/Chronicle-Map#108]
Per-segment stats consist of one or more per-tier stats.

Per-tier stats could include:
 - Number of entries stored. Number of entries stored / hashLookup capacity = hashLookup load factor.
 - Number of payload bytes stored: keys, values, key sizes, value sizes, other payload, total.
 - Number of chunks used. Number of chunks used * chunk size - total number of payload bytes stored = internal fragmentation.
 - Number of continuous free chunks in the end of the entries area. Size of entries area in chunks - Number of continuous free chunks in the end of the entries area - Number of chunks used = "external fragmentation".

**Comment by minborg** [comment]
Closing as wontfix
