### ISSUE TITLE
ClassNotFoundException when using Chronicle in PlayFramework Development Mode

### ISSUE THREAD

**Issue by domdorn** [OpenHFT/Chronicle-Map#109]
When using chronicle-map together with the PlayFramework 2.5.x and using a persistent storage file, during development after every file change, I get a 

> play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[RuntimeException: java.lang.ClassNotFoundException: xxx.xxx.xxx.browserdetection.rest.protocol.v1.MinimalResponseImpl]]
> 	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:293)
> 	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:220)
> 	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:160)
> 	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:188)
> 	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:100)
> 	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:100)
> 	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:99)
> 	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:346)
> 	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:345)
> 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
> Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: xxx.xxx.xxx.browserdetection.rest.protocol.v1.MinimalResponseImpl
> 	at net.openhft.chronicle.hash.serialization.impl.SerializableReader.read(SerializableReader.java:46)
> 	at net.openhft.chronicle.hash.serialization.impl.SerializableReader.read(SerializableReader.java:37)
> 	at net.openhft.chronicle.hash.serialization.impl.SerializableReader.read(SerializableReader.java:32)
> 	at net.openhft.chronicle.map.VanillaChronicleMap.searchValue(VanillaChronicleMap.java:632)
> 	at net.openhft.chronicle.map.VanillaChronicleMap.tieredValue(VanillaChronicleMap.java:566)
> 	at net.openhft.chronicle.map.VanillaChronicleMap.optimizedGet(VanillaChronicleMap.java:518)
> 	at net.openhft.chronicle.map.VanillaChronicleMap.get(VanillaChronicleMap.java:467)
> 	at xxx.xxx.xxx.browserdetection.persistence.PersistentUserAgentStore.get(PersistentUserAgentStore.java:22)
> 	at browserdetection.services.impl.BrowserDetectionServiceStoringImpl.findMatch(BrowserDetectionServiceStoringImpl.java:40)
> 	at browserdetection_v1.yaml.Browserdetection_v1Yaml$$anonfun$1.apply(browserdetection_v1.yaml.scala:48)
> Caused by: java.lang.ClassNotFoundException: xxx.xxx.xxx.browserdetection.rest.protocol.v1.MinimalResponseImpl
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	at java.lang.Class.forName0(Native Method)
> 	at java.lang.Class.forName(Class.java:348)
> 	at java.io.ObjectInputStream.resolveClass(ObjectInputStream.java:628)
> 	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1620)
> 	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1521)
> 	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1781)
> 	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
> 

This happens only in developing mode (so production is fine), but makes developing quite annoying. 

After some debugging, it looks like the problem is, that the ValueReader (SerializableReader) in the VanillaChronicleMap is not using the Classloader that is used when instantiating the map, but another one. 

![image](https://cloud.githubusercontent.com/assets/100349/22021089/a0e79d68-dcbb-11e6-801f-0fa3cf1b1c9e.png)

![image](https://cloud.githubusercontent.com/assets/100349/22021102/b5c8047a-dcbb-11e6-9049-0804e44caaf3.png)

According to this stackoverflow answer ( http://stackoverflow.com/a/24874972/979507 ), a solution would be to use a subclass of ObjectInputStream that uses the correct classLoader in the resolveClass method. 

Is there another way than changing SerializableReader of Chronicle-Map ? 
Any help is greatly appreciated!

Thanks,
Dominik

**Comment by leventov** [comment]
Also you might want to provide really custom serializers for your key/value types rather than falling back to Java built-in serialization, because it is very inefficient at the moment. https://github.com/OpenHFT/Chronicle-Bytes/issues/32 could improve this, though.

**Comment by minborg** [comment]
@RobAustin Can we close this and leave Map as it is?
