### ISSUE TITLE
Readonly support

### ISSUE THREAD

**Issue by AlexBischof** [OpenHFT/Chronicle-Map#116]
We have the problem that we have two physically seperated networks and want to share data between them, which changes rarely. So we have on the one side an exporter which generates a CM-file and on the other side a client which uses the transfered file. Unfortunately the client side gets the file from a readonly mount which can not be change.
This leads to an error in _CanonicalRandomAccessFiles_ because of 
` return new RafReference(new RandomAccessFile(f, "rw"));`

Is it possible to provide a flag within _ChronicleMapBuilder_?

**Comment by leventov** [comment]
Technically, it is possible. I was thinking about this feature. However currently other issues marked [Roadmap](https://github.com/OpenHFT/Chronicle-Map/milestone/1) are higher in my personal priority list.

**Comment by minborg** [comment]
Closing as wontfix
