### ISSUE TITLE
what is the difference with redis

### ISSUE THREAD

**Issue by huangyiminghappy** [OpenHFT/Chronicle-Map#119]
hi，i notice that Chronicle-map can sharding map by tcp or direMemory，and i want to know  what is the difference with redis,and what is the Special scene? thank you !

**Comment by leventov** [comment]
Pro Chronicle Map:
 - Chronicle Map is scalable (a lot of threads could write and read data to/from Chronicle Map concurrently without blocking each other), Redis is single-threaded.
 - Chronicle Map usually has lower overhead per entry than Redis, but it's less robust: [doesn't support resizing well properly yet](https://github.com/OpenHFT/Chronicle-Map/issues/105), suffers memory fragmentation in some cases.
 - Inter-process communication via shared memory, Redis doens't have this.

Pro Redis:
 - Redis has Cluster solution and client-server support out of the box. All distributed flavors of Chronicle Map are closed source. Client-server communication with Chronicle Map is supposed to be done via [Chronicle Engine](https://github.com/OpenHFT/Chronicle-Engine) but it support only legacy Chronicle Map 2 in the open-source version, Chronicle Map 3 support is closed source.
