### ISSUE TITLE
wrong contact url

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [OpenHFT/Chronicle-Map#12]
the contact url on this page
https://github.com/OpenHFT/Chronicle-Map

does not work; it points to
https://github.com/OpenHFT/Chronicle-Map/blob/master/sales@higherfrequencytrading.com

**Comment by BoundedBuffer** [comment]
I've check the URL and it looks ok to me, can you give me a bit more detail about the problem ( maybe Im looking at the wrong URL ) - thanks Rob

**Comment by Andrei-Pozolotin** [comment]
when I click on it
https://github.com/OpenHFT/Chronicle-Map/blob/master/sales@higherfrequencytrading.com

I get

![image](https://cloud.githubusercontent.com/assets/1622151/5740006/0178833e-9bc5-11e4-8fa7-b0dbec100e4c.png)

**Comment by BoundedBuffer** [comment]
can you send me a screen shot of where this link is on the page - thanks

**Comment by Andrei-Pozolotin** [comment]
it was here
![image](https://cloud.githubusercontent.com/assets/1622151/5740110/1dd49d3c-9bc6-11e4-8807-60f30c9a3dbd.png)

but it works now :-)

**Comment by BoundedBuffer** [comment]
thanks

**Comment by lptilokchandani** [comment]
I am also facing the same issue. Is this resolved?
