### ISSUE TITLE
Sequential memory iteration

### ISSUE THREAD

**Issue by leventov** [OpenHFT/Chronicle-Map#121]
Currently iteration is done sequentially over [the hash lookup](https://github.com/OpenHFT/Chronicle-Map/blob/master/spec/3-memory-layout.md#hash-lookup) area, _but_, as a consequence, randomly over [the entry space](https://github.com/OpenHFT/Chronicle-Map/blob/master/spec/3-memory-layout.md#entry-space), where the main payload data is stored. This issue to about exploring possibility to implement iteration sequentially over the entry space, using [the free list bitmap](https://github.com/OpenHFT/Chronicle-Map/blob/master/spec/3-memory-layout.md#free-list), that should improve the speed of iteration.

**Comment by minborg** [comment]
Closing as wontfix
