### ISSUE TITLE
Chronicle map delay after refreshing

### ISSUE THREAD

**Issue by osnatn1984** [OpenHFT/Chronicle-Map#122]
I am using chronicle map in order to save data from the database into chronicle map files.
I notice that each time there is a lot of new information in the database, the synchronization of this information stuck the reading access for the chronicle map files to several seconds.
I want to know if this is a known issue, and if it is - is there any way to overcome it.

Thanks,
Osnat.

**Comment by peter-lawrey** [comment]
How are you doing the refresh, in particular are you doing anything which
holds a lock?

Regards,
Peter.
ᐧ

**Comment by osnatn1984** [comment]
No…
Just a simple chronicleMap.put

**Comment by peter-lawrey** [comment]
When you perform a put, you should be able to do a get concurrently (or
pretty close to it)  You might see a slowdown of the machine if the map is
larger than main memory but if it fits in main memory, it is not expected
you should have a problem.
ᐧ

**Comment by leventov** [comment]
@osnatn1984 

> I notice that each time there is a lot of new information in the database, the synchronization of this information stuck the reading access for the chronicle map files to several seconds.

Sorry I wasn't really able to understand what did you mean, could you please describe the problem more specifically?

**Comment by RobAustin** [comment]
closing as there has been no response for 2 years.
