### ISSUE TITLE
I have created a chronicle map. passed a dat file, but when I try changing some data. map size is increasing but the dat file is not getting updated with the data

### ISSUE THREAD

**Issue by purnima2006** [OpenHFT/Chronicle-Map#129]

**Comment by leventov** [comment]
Please post a reporoducible example of your problem

**Comment by maria-sekar** [comment]
Hi,
This is Maria sekar.
I also got the same issue .
Here is the scenario, 
In the first run I created the map file for caching.
In the second run while adding new entries sometime only the program is running afterwards everthing sits idle. I have to manually killed the main thread.

**Comment by leventov** [comment]
@maria-sekar could you post runnable code that reproduces this issue?

**Comment by maria-sekar** [comment]
Hi @leventov,
Thanks for your reply.
In my case its occurring while processing the heavy amount of data (above 20GB ).

`import java.io.File;
import java.io.IOException;
import java.util.concurrent.ConcurrentMap;

import com.typesafe.config.Config;
import com.xoanon.andes.core.crypt.ICrypto;
import com.xoanon.andes.core.util.OpenHftSerializer;

import net.openhft.chronicle.map.ChronicleMap;

public abstract class AbstractAndes implements IAndes {

	protected final ICrypto cyptoHandler;
	protected final Config config;
	protected IPiiDataValidator piiDataValidator;

	public AbstractAndes(final Config config, final ICrypto cyptoHandler) throws AndesException {
		this.config = config;
		this.cyptoHandler = cyptoHandler;
	}

	protected static final ConcurrentMap<String, String> createMap(String cacheName) {
		try{
			final ConcurrentMap<String, String> CACHE_MAP = ChronicleMap
				    .of(String.class, String.class)
				    .name(cacheName)
				    .averageKeySize(50)
				    .averageValueSize(175)
				    .entries(1000000)
				    .keyMarshaller(new OpenHftSerializer<>())
				    .valueMarshaller(new OpenHftSerializer<>())
				    .maxBloatFactor(10)
				    .actualSegments(16)
				    .createOrRecoverPersistedTo(new File("./cache/" + cacheName + ".db"));
			return CACHE_MAP;
		} catch(IOException e) {
			System.out.println(e);
		}
		return null;
	}
}

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import net.openhft.chronicle.bytes.Bytes;
import net.openhft.chronicle.core.annotation.NotNull;
import net.openhft.chronicle.core.util.ReadResolvable;
import net.openhft.chronicle.hash.serialization.BytesReader;
import net.openhft.chronicle.hash.serialization.BytesWriter;
import net.openhft.chronicle.wire.WireIn;
import net.openhft.chronicle.wire.WireOut;

@SuppressWarnings("unchecked")
public final class OpenHftSerializer<T> implements BytesReader<T>, BytesWriter<T>, ReadResolvable<OpenHftSerializer<T>>{

	private static final Logger LOGGER = LoggerFactory.getLogger(OpenHftSerializer.class);
	private final Serializer<T> SERIALIZER;

    public OpenHftSerializer() {
    	this.SERIALIZER = new Serializer<T>((Class<T>) AndesUtil.getTypeArguments(OpenHftSerializer.class, this.getClass()).get(0));
	}

	@Override
	public void write(Bytes out, T toWrite) {
		try {
			byte[] serizliedBytes = this.SERIALIZER.serialize(toWrite);
			out.writeInt(serizliedBytes.length);
			out.write(serizliedBytes, 0, serizliedBytes.length);
		} catch (Exception e) {
			LOGGER.error("Error while persisting data.", e);
		}
	}

	@Override
	public T read(Bytes in, T using) {
		try {
			int serializedBytesLength = in.readInt();
			byte[] serizliedBytes = new byte[serializedBytesLength];
			in.read(serizliedBytes, 0, serializedBytesLength);
			using = this.SERIALIZER.deserialize(serizliedBytes);
		} catch (Exception e) {
			LOGGER.error("Error while reading data.", e);
		}
		return using;
	}

    public void writeMarshallable(@NotNull WireOut wireOut) {
        // no fields to write
    }

    public void readMarshallable(@NotNull WireIn wireIn) {
        // no fields to read
    }

	@Override
	public OpenHftSerializer<T> readResolve() {
		return this;
	}
}

import java.io.ByteArrayOutputStream;
import java.io.InputStream;
import java.io.Serializable;
import java.nio.ByteBuffer;
import java.util.Queue;
import java.util.concurrent.ConcurrentLinkedQueue;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.esotericsoftware.kryo.Kryo;
import com.esotericsoftware.kryo.io.Input;
import com.esotericsoftware.kryo.io.Output;
import com.xoanon.andes.core.AndesException;

@SuppressWarnings("serial")
public class Serializer<T> implements Serializable {

	private static final Logger LOGGER = LoggerFactory.getLogger(Serializer.class);
	private final KryoPool kryoPool = new KryoPoolImpl();
	private Class<T> persistentClass;

	public interface KryoPool {
		Kryo get();
		void yield(Kryo kryo);
	}

	public static final class KryoPoolImpl implements KryoPool {

		private final Queue<Kryo> objects = new ConcurrentLinkedQueue<Kryo>();

		public KryoPoolImpl() {
		}

		public Kryo get() {
			Kryo kryo;
			if ((kryo = objects.poll()) == null) {
				kryo = createInstance();
			}
			return kryo;
		}

		public void yield(Kryo kryo) {
			objects.offer(kryo);
		}

		/**
		 * Sub classes can customize the Kryo instance by overriding this method
		 *
		 * @return create Kryo instance
		 */
		private Kryo createInstance() {
			Kryo kryo = new Kryo();
			kryo.setReferences(false);
			return kryo;
		}

	}

    public Serializer(Class<T> persistentClass) {
    	this.persistentClass = persistentClass;
	}

    public final byte[] serialize(T object) throws AndesException {
		byte[] serializedBytes = null;
		Kryo kryo = null;
		try {
			kryo = kryoPool.get();
			ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream(150);
	    	Output output = new Output(byteArrayOutputStream);
	    	kryo.writeObject(output, object);
	        serializedBytes = output.toBytes();
		} catch(Exception e) {
			LOGGER.error("Error while serializing the object.", e);
			e.printStackTrace();
		} finally {
            if (kryo != null) {
                this.kryoPool.yield(kryo);
            }
        }
		return serializedBytes;
    }

    public T deserialize(InputStream inputStream) throws AndesException {
		Kryo kryo = null;
		try {
			if(inputStream != null && this.persistentClass != null) {
				kryo = kryoPool.get();
				return (T) kryo.readObject(new Input(inputStream), this.persistentClass);
			}
		} catch(Exception e) {
			LOGGER.error("Error while deserializing the bytes.", e);
			throw new AndesException("Error while serializing the object.", e);
		} finally {
            if (kryo != null) {
                this.kryoPool.yield(kryo);
            }
        }
		return null;
    }
	
	public final T deserialize(byte[] bytes) throws AndesException {
		Kryo kryo = null;
		try {
			if(bytes != null && bytes.length > 0 && this.persistentClass != null) {
				kryo = kryoPool.get();
				return (T) kryo.readObject(new Input(bytes), this.persistentClass);
			}
		} catch(Exception e) {
			LOGGER.error("Error while deserializing the bytes.", e);
			throw new AndesException("Error while serializing the object.", e);
		} finally {
            if (kryo != null) {
                this.kryoPool.yield(kryo);
            }
        }
		return null;
    }

	public void serialize(T value, ByteBuffer buf) {
		byte[] bytes = null;
		try {
			bytes = this.serialize(value);
	        buf.put(bytes);
		} catch (AndesException e) {
			LOGGER.error("Error while serializing the object.", e);
			e.printStackTrace();
		} catch (Exception e) {
			LOGGER.error("Error while serializing the object.", e);
			e.printStackTrace();
		}
	}

	public T deserialize(ByteBuffer buf) {
		T deserializedObj = null;
        try {
        	byte[] bytes = new byte[buf.capacity()];
        	buf.get(bytes);
        	deserializedObj = this.deserialize(bytes);
		} catch (AndesException e) {
			LOGGER.error("Error while de-serializing the byte to object.", e);
		}
        return deserializedObj;
	}

	public int serializedSize(T value) {
		int objectSize = 0;
		try {
			objectSize = this.serialize(value).length;
		} catch (AndesException e) {
			LOGGER.error("Error while calculating the serialized object size.", e);
		}
		return objectSize;
	}
}



`

**Comment by leventov** [comment]
@maria-sekar from the Chronicle Map configuration, it doesn't add up - you configure 1 000 000 entries with 225 bytes of average size, that should 225 MB, not 20 GB.

BTW, why do you configure actualSegments explicitly?

Also BTW, your serialization is inefficient - from Kryo you can write directly to `Bytes.outputStream()` instead of `ByteArrayOutputStream`. Same for deserialization. Also instead of writing and reading sizes yourself, you can use [`SizedWriter` and `SizedReader`](https://github.com/OpenHFT/Chronicle-Map#sizedwriter-and-sizedreader). And for stateful serialization (Kryo objects), you should embrace [`StatefulCopyable`](https://github.com/OpenHFT/Chronicle-Map#understanding-statefulcopyable).

**Comment by minborg** [comment]
I am closing this issue now as per the suggestions made in leventov's answer. Please reopen the issue if the problem persists.
