### ISSUE TITLE
How to delete a file located inside Chronicle Queue?

### ISSUE THREAD

**Issue by osnatn1984** [OpenHFT/Chronicle-Map#131]
Hi,

I am using ChronicleQueue object to perform some files processing. I notice that when I am trying to delete a file in linux while it is still in the chronicle – the file is not completely deleted (it still holds space in the memory and you can see it using the " lsof +L1" command).
The file can be completely deleted if the queue is closed, but this means it can't process other files in the queue as well…
Do you have any idea how we can delete one file from the queue without closing the queue completely?

Thanks,
Osnat.

**Comment by leventov** [comment]
I think this question should be asked in this repository: https://github.com/OpenHFT/Chronicle-Queue
