### ISSUE TITLE
Handling Recovery of ChronicleMap across Spark Executors

### ISSUE THREAD

**Issue by gowrishankarsundersc** [OpenHFT/Chronicle-Map#133]
We want to use ChronicleMap in Apache Spark on the workers to store a shared cache within a VM. Currently, we are using Hazelcast to share the cache but obviously, being able to use off-heap memory for free and also avoiding tcp-ip (even over 127.0.0.1) are things we like about ChronicleMap which is why we want to be able to use it.The idea is for all the executors which land within the same physical machine to share the cache and the cache will be persisted to tmpfs so that it stays valid till the VM itself is alive (we dont need the values to be persisted across instance lifecycles) and any worker joining could start using it. We ideally need LRU eviction on the keys stored and although ChronicleMap does not support it, given its usage of off-heap memory, I guess we could live with that restriction but what is more concerning is its requirement to recover from crashes during access exclusively which is a problem in our setup.

For example, lets say we have 5 executors running on the same VM sharing the cache and one of the VMs crashes during an access corrupting the cache. There is no way for the other executors to know about this, have only one of them recover while everyone wait. If at least it was guaranteed that concurrent recovery or access during a recovery or on a corrupted cache would throw some exception, it would help because then, everyone failing on access can try acquiring a file lock and then begin the recovery process and anyone else accessing during this time might receive another exception indicating that recovery is ongoing and finally, the cache is fixed and things are back to normal but from the docs, it looks like the behavior is just undefined which leaves too many doubts.

Is it possible to get ChronicleMap working in our setup? Has anyone else had success getting it to work in Apache Spark, given these requirements? Any advice would help. Since executor failures are rare, we are even fine with throwing away the cache and filling it back in upon corruption but the troubling part is synchronously identifying corruption across executors on the same VM.

Thanks

**Comment by TerryW9** [comment]
Good Morning, Gowri.

Thank you for your question.

I will find out if this is possible and get back to you as soon as possible.

Best Regards,
Terry

**Comment by peter-lawrey** [comment]
Chronicle Map is a segmented hash map to support concurrency.   
Killing your OS, or a kill -9 of the process could leave one of the segments in a corrupt state.
However, throwing an exception/error or killing the JVM normally shouldn't cause such a corruption.
There is no way to detect a corruption without accessing the segment corrupted.

I suggest you instead detect the process or OS has died, and create a new cache when this happens.

**Comment by minborg** [comment]
I assume you fixed the issue @gowrishankarsundersc using @peter-lawrey tips on detecting process death. If not, please reopen this issue.
