### ISSUE TITLE
Mixed values

### ISSUE THREAD

**Issue by ospavel** [OpenHFT/Chronicle-Map#137]
I try communicate between jvms on the same machine and get strange error.

Simplified code:
interface:
```
public interface SharedData {
    double getVl1();
    void setVl1(double vl1);
    double getVl2();
    void setVl2(double vl2);
    double getVl3();
    void setVl3(double vl3);
    double getVl4();
    void setVl4(double vl4);
    double getVl5();
    void setVl5(double vl5);
}
```

jvm1 (writer):
```
new Thread(() -> {
  ChronicleMap<Integer, SharedData> sharedDataChronicleMap = ChronicleMap
                        .of(Integer.class, SharedData.class).name(MAP_DATA_NAME).entries(1)
                        .createOrRecoverPersistedTo(new File(MAP_DATA_FNAME), false);
   SharedData tmpSharedData = Values.newHeapInstance(SharedData.class);

   tmpSharedData.setVl1(1.0);
   tmpSharedData.setVl2(2.0);
   tmpSharedData.setVl3(3.0);
   tmpSharedData.setVl4(4.0);
   tmpSharedData.setVl5(5.0);
   sharedDataChronicleMap.put(0, tmpSharedData);

   Thread.sleep(MILLISECONDS_1HOUR);
}).start();
```

jvm2 (reader):
```
  ChronicleMap<Integer, SharedData> sharedDataChronicleMap = ChronicleMap
                    .of(Integer.class, SharedData.class).name(MAP_DATA_NAME).entries(1)
                    .createPersistedTo(new File(MAP_DATA_FNAME));
  SharedData tmpSharedData = Values.newHeapInstance(SharedData.class);

  sharedDataChronicleMap.getUsing(0, tmpSharedData);
  logger.info("{} {} {} {} {}", tmpSharedData.getVl1(), tmpSharedData.getVl2(), tmpSharedData.getVl3(), tmpSharedData.getVl4(), tmpSharedData.getVl5());
```

I should receive 1.0 2.0 3.0 4.0 5.0, but I receive: 1.0 4.0 3.0 2.0 5.0 - values are mixed.
Sometimes on restarting jvm2 code (without touching jvm1) I get right values also.

What's wrong? Where is the mistake?

**Comment by leventov** [comment]
Please try to ensure order using `@Group` annotation: https://github.com/OpenHFT/Chronicle-Values#field-ordering-in-flyweight-layout.

**Comment by ospavel** [comment]
Ok, I'll try when I get to computer, but using @Group not specified in the examples. Is this normal?

I tried to remove get/set from interface methods names and change them to firstA, secondB and so on. The result was mixing as reverse order...

**Comment by ospavel** [comment]
Ok, @Group works. Thank you.

**Comment by leventov** [comment]
Yes, it should work without Group annotations. It's a bug that it doesn't.

**Comment by minborg** [comment]
I am closing this issue as the `@Group` annotations appear to have fixed the issue.
