### ISSUE TITLE
ChronicleMap createPersistedTo hang

### ISSUE THREAD

**Issue by delawr0190** [OpenHFT/Chronicle-Map#138]
Hello,

I'm experiencing very long application start-up times with the following ChronicleMap configuration:

chunkSize : 256
chunksPerSegmentTier : 39629
segments : 65536

It's taking roughly 103 seconds to initialize the map with the configuration above on a 32 core 2.6 GHz 256 GB RAM server (CentOS).  The stack trace indicates a hang here:

`net.openhft.chronicle.hash.impl.util.jna.PosixMsync.msync`

Should be ~664 GB map residing on a 1.3 TB HDD.

The startup time seems to exponentially get worse as more disk is leveraged.  Once the application is up, however, things seem to behave properly.

Is anybody able to provide any guidance?  Would be greatly appreciated.

**Comment by leventov** [comment]
Chronicle Map is not designed to handle bigger-than-memory volume of data (664 vs. 256 in your case), see this section in the spec: https://github.com/OpenHFT/Chronicle-Map/blob/master/spec/1-design-goals.md#assumptions-1

I recommend to use some LSM-like store, e. g. RocksDB

**Comment by delawr0190** [comment]
Thanks for the response! I’ll go ahead and see how that works out for me.
