### ISSUE TITLE
Considering another licence?

### ISSUE THREAD

**Issue by dustContributor** [OpenHFT/Chronicle-Map#141]
Hi! I came across your project and I think it's what I am looking for (in-memory and/or file persisted key-value store focused on low latency and low garbage).

Thing is, it's LGPL licenced. I'd have no issues with contributing back modifications, but the issue is that LGPL puts a heavy condition on the library user's software: They have to allow reverse engineering. In theory, it's only for the purpose of say, switching the lib version with a newer one. But "purpose" seems pretty hard to prove in such cases.

Have you considered another licence that doesn't put this restriction on your users? I imagine you're not very interested in reverse engineering their software, but you're interested in any modification that could benefit your project in return.

Have in mind that mine is a hobby project (a game, hopefully, someday :smile:), so I probably don't represent your demographic at all, it's just a suggestion.

I think something like [Mozilla Public Licence](https://en.wikipedia.org/wiki/Mozilla_Public_License) would fit the bill. [Mozilla Public Licence FAQ](https://www.mozilla.org/en-US/MPL/2.0/FAQ/). As far as I understand, modified sources under MLP have to be MLP licenced too, which would allow you to benefit from the modifications of your library, and it lacks the reverse engineering clause that LGPL has.

**Comment by dpisklov** [comment]
I think you misunderstand the LGPL clause about reverse engineering:

> You may convey a Combined Work under terms of your choice that,
> taken together, effectively do not restrict modification of the
> portions of the Library contained in the Combined Work and reverse
> engineering for debugging such modifications

The reverse engineering of modifications to Library, not for the code that uses the Library.
I.e. if you use this library in your maven project, and/or include the jar with your distribution, then all you need to do is provide information that this library is LGPL licensed and source code for it is here.
That said, we use Apache 2.0 for our open-source projects, I'm trying to figure out why Map was given an exception from that rule...

**Comment by leventov** [comment]
@dpisklov because I preferred my contributions that happened since January 2016 onwards to stay LGPL licensed.

**Comment by dustContributor** [comment]
> I think you misunderstand the LGPL clause about reverse engineering

Why would it specify a reverse engineering clause for library code only if, given by the licence, the user already has the modified library's sources? That paragraph refers to the "combined work".

In any case, it's not an agreed upon thing, here is a link that tries to support your POV on the clause for instance: 

http://opensource.telekom.net/oslic/releases/oslic-reveng-extract.pdf

It's not short and it's complex. It tries really really hard to organize the structure of that paragraph so it reads like you say **if** the library is dynamically linked. Even then, the author mentions Java's case specifically and argues that Java's linking method could be interpreted as static linking (you can read his reasoning there), thus allowing the reverse engineering of the "combined work" anyway.

You'll find links arguing the contrary too Googling a bit. In short, I think the only way that we'd find out is in a local court based on the interpretation of the judge, if such matters ever get that far. 

I insist LGPL isn't a good idea if your original purpose wasn't specifically allowing for reverse engineering of your users' software.

**Comment by dpisklov** [comment]
I woudn't care about who says what somewhere on the internet. The official body who developed the license is GNU. Here's their official position:
https://www.gnu.org/licenses/lgpl-java.en.html

> FSF's position has remained constant throughout: the LGPL works as intended with all known programming languages, including Java. Applications which link to LGPL libraries need not be released under the LGPL. Applications need only follow the requirements in section 6 of the LGPL: allow new versions of the library to be linked with the application; and allow reverse engineering to debug this.

And they clarify what exactly means reverse engineering:

> If you distribute a Java application that imports LGPL libraries, it's easy to comply with the LGPL. Your application's license needs to allow users to modify the library, and reverse engineer your code to debug these modifications. This doesn't mean you need to provide source code or any details about the internals of your application. Of course, some changes the users may make to the library may break the interface, rendering the library unable to work with your application. You don't need to worry about that—people who modify the library are responsible for making it work.

So in your case, you simply need to include a clause in YOUR license that you permit your users to "modify the library, and reverse engineer your code to debug these modifications." Note that this allows reverse engineering of only those parts that linked to the library.

As such I don't see any reason for changing the license for us, especially when we have a major contributor who objects. Hence I close this as wontfix.

**Comment by hft-team-city** [comment]
Released in Chronicle-Map-3.14.6 (https://github.com/OpenHFT/Chronicle-Map/releases/chronicle-map-3.14.6), BOM-1.15.271 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-1.15.271)

**Comment by hft-team-city** [comment]
Released in Chronicle-Map-3.14.6 (https://github.com/OpenHFT/Chronicle-Map/releases/chronicle-map-3.14.6), BOM-1.15.272 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-1.15.272)

**Comment by hft-team-city** [comment]
Released in Chronicle-Map-3.14.6 (https://github.com/OpenHFT/Chronicle-Map/releases/chronicle-map-3.14.6), BOM-1.15.274 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-1.15.274)

**Comment by dagnelies** [comment]
The license is IMHO suboptimal since it cannot be used in any MIT / BSD / Apache licensed project.

Moreover, I'd argue like @dustContributor that the LGPL is problematic in proprietary software too since its terms are complex, unpractical, subject to frequent debate and a PITA. For instance, the stance of our company is to avoid using libraries under this license because of this.

Basically, it can only be used by people not caring about the license or for LGPL / GPL products. This is IMHO a heavy constraint.

**Comment by dpisklov** [comment]
@dagnelies we can't cater for companies/people who don't understand license, and change our licensing accordingly. As I explained in a comment above, there's a clear explanation from FSF on what the LGPL means which we (Chronicle) support. And that's by far is NOT 

> it can only be used by people not caring about the license or for LGPL / GPL products

Contrary, LGPL can be easily used in proprietary applications and it's really easy to comply with its terms (as long as one reads it as is outlined by people who wrote it and who essentially enforce it, instead of trusting questionable sources of information telling otherwise).

**Comment by keiran-lawrey** [comment]
Companies who pay to use our Commercial version can have any license they
need. We could do one which suits you on a commercial basis.

Peter.
