### ISSUE TITLE
Links from javadocs to the docs on Github are broken since the doc reorganization

### ISSUE THREAD

**Issue by leventov** [OpenHFT/Chronicle-Map#142]
Since the Chronicle Map tutorial is reorganized (split into multiple .adoc pages), links from the Javadoc to the tutorial are broken, for example, https://github.com/OpenHFT/Chronicle-Map/blob/4bcdcdb8cee4c87a677e9ee71fbf6d481b0d9277/src/main/java/net/openhft/chronicle/hash/ChecksumEntry.java#L30. There are more than just one, search for "github" in the source code tree.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Map-3.22ea6](https://github.com/OpenHFT/Chronicle-Map/releases/chronicle-map-3.22ea6), [BOM-2.22ea86](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea86)
