### ISSUE TITLE
BytesMarshallable and value classes not supported

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Map#151]

**Comment by peter-lawrey** [comment]
Added an exception for now.

**Comment by peter-lawrey** [comment]
Would be nice to support this option.

**Comment by hft-team-city** [comment]
Released in Chronicle-Map-3.14.6 (https://github.com/OpenHFT/Chronicle-Map/releases/chronicle-map-3.14.6), BOM-1.15.271 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-1.15.271)

**Comment by hft-team-city** [comment]
Released in Chronicle-Map-3.14.6 (https://github.com/OpenHFT/Chronicle-Map/releases/chronicle-map-3.14.6), BOM-1.15.272 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-1.15.272)

**Comment by hft-team-city** [comment]
Released in Chronicle-Map-3.14.6 (https://github.com/OpenHFT/Chronicle-Map/releases/chronicle-map-3.14.6), BOM-1.15.274 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-1.15.274)
