### ISSUE TITLE
Nested primitive maps support

### ISSUE THREAD

**Issue by telles-simbiose** [OpenHFT/Chronicle-Map#152]
Hi there,

I am trying to come up with an offheap version of this structure, which is the main source of garbage on my software:
`Map<FlushEntryKey, TIntObjectMap<Map<String, IdsAndCountsToInsert>>>`

Where `FlushEntryKey` is na easily serializable tuple, `TIntObjectMap` is trove's alternative for `Map<Integer, Object>` and `IdsAndCountsToInsert` is either a `TIntSet` or `TIntIntMap`, both from trove collections.

It seems that I would need to create custom serializer for `TIntObjectMap<Map<String, IdsAndCountsToInsert>>` and each time that I need to update some entry on this nested map it would deserialize, modify and serialize again, is that correct?

Is it feasible to use Chronicle Map in this case or other solution to achieve zero garbage collection with a structure like that?

Thanks so much.

**Comment by leventov** [comment]
I think some tree-like store (e. g. LMDB) with triplet key (FlushEntryKey-String) should work better for you task than Chronicle Map, if LMDB provides appropriate key-range API (even if it doesn't, it should be possible to add such, because the data structure enables it fundamentally).

**Comment by leventov** [comment]
P. S. Don't use trove, it's slow, buggy and unsupported. Use either fastutil or Koloboke.
