### ISSUE TITLE
Fixed MemoryLeaksTest.testExplicitChronicleMapCloseReleasesMemory

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Map#153]
see http://teamcity.higherfrequencytrading.com:8111/repository/download/OpenHFT_ReleaseJob_ReleaseByArtifact/255301:id/ReleaseAutomation/projects/chronicle-map-runTests-1527068168717.log

**Comment by tgd** [comment]
Closing this out as no work is planned on this at the moment. Please comment on this issue if you would like it re-opened. If you would like to expedite the development of this please get in touch with us here for commercial support: https://chronicle.software/contact-us/
