### ISSUE TITLE
Are the v2 and v3 file formats compatible?

### ISSUE THREAD

**Issue by cristaloleg** [OpenHFT/Chronicle-Map#156]
Hi, I'm going to migrate from v2 to v3 and I'm trying to find info regarding file formats.
- Are they compatible?
- Is it safe to give to v3 instance a v2 file?
- Any corner cases?

Thanks.

**Comment by dpisklov** [comment]
@cristaloleg 
Please refer to the documentation here:
https://github.com/OpenHFT/Chronicle-Map/tree/master/docs
In particular:
https://github.com/OpenHFT/Chronicle-Map/blob/master/docs/CM_Updates.adoc

Short answer is - no, the file format is incompatible.

PS please do not use github for questions - stackoverflow is the Q&A platform and we monitor it.

**Comment by hft-team-city** [comment]
Released in Chronicle-Map-3.16.1 (https://github.com/OpenHFT/Chronicle-Map/releases/chronicle-map-3.16.1), BOM-1.16.175 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-1.16.175)

**Comment by hft-team-city** [comment]
Released in Chronicle-Map-3.16.1 (https://github.com/OpenHFT/Chronicle-Map/releases/chronicle-map-3.16.1), BOM-1.16.201 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-1.16.201)
