### ISSUE TITLE
Create JLBH test for Map

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Map#164]
-Need new latency test of a 4096 byte put into Map.  Results distributed as a histogram of P50, P95 and P99

-Need new latency test of a 4096 byte read from Map.  Results distributed as a histogram of P50, P95 and P99

**Comment by dpisklov** [comment]
4096 bytes key size, value size, each or combined?

**Comment by hft-team-city** [comment]
Released in Chronicle-Map-3.17.0 (https://github.com/OpenHFT/Chronicle-Map/releases/chronicle-map-3.17.0), BOM-2.17.48 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.48)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Map-3.17.0](https://github.com/OpenHFT/Chronicle-Map/releases/chronicle-map-3.17.0), [BOM-2.17.50](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.50)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Map-3.17.0](https://github.com/OpenHFT/Chronicle-Map/releases/chronicle-map-3.17.0), [BOM-2.17.52](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.52)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Map-3.17.0](https://github.com/OpenHFT/Chronicle-Map/releases/chronicle-map-3.17.0), [BOM-2.17.53](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.53)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Map-3.17.0](https://github.com/OpenHFT/Chronicle-Map/releases/chronicle-map-3.17.0), [BOM-2.17.72](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.72)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Map-3.17.0](https://github.com/OpenHFT/Chronicle-Map/releases/chronicle-map-3.17.0), [BOM-2.17.74](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.74)
