### ISSUE TITLE
ConcurrentModificationException： Context shouldn't be ac cessed from multiple threads

### ISSUE THREAD

**Issue by pinggaimuir** [OpenHFT/Chronicle-Map#165]
java.util.ConcurrentModificationException:ChronicleMap{name=null,file=/home/kaifa/dcrawler/CrawlerSpiderStarter/tmp/PointCache, identityHashCode=1660291605}: Context shouldn't be accessed from multiple threads

这个问题怎么解决啊 ，求大神，我调用map.remove()方法时产生的

**Comment by dpisklov** [comment]
@pinggaimuir Unfortunately we don't have anyone who can understand the hieroglyphs.
Although the error message is pretty obvious and means you are using something in multiple threads which is not supposed to be used in multithreaded manner. I can't see the code so I can't really say what is that something but it should be pretty obvious from the stacktrace.

**Comment by RobAustin** [comment]
suggestion use an iterator and call remove from within there, however, this is a total guess as there is not enough to go on to see what the problem is you are having.
