### ISSUE TITLE
Is ChronicleMap an improved Concurrent HashMap?

### ISSUE THREAD

**Issue by complone** [OpenHFT/Chronicle-Map#170]
Hello, Excuse me,because  of I need to refer to this project recently, by looking at the source code of this project:

according to ```ChronicleHash``` class inheritance graph
   - it is responsible for the memory management of each object in the JVM heap area
   - it inherits from HashSegFrament to perform lock segmentation similar to courrent HashMap, in which similar lock segmentation granularity settings can be seen.

For example: ```int segments (); ```

but look at the courrent HashMap, wo'shi'fou'ke'mentioned in the project's [workflow](https://github.com/OpenHFT/Chronicle-Map/blob/master/docs/CM_Replication.adoc#how-chronicle-map-replication-works)

   it's provided by the project, can I understand that the project is rebuilt on courrent HashMap, which is actually Chronicle Map?

**Comment by dpisklov** [comment]
Chronicle Map has no relation to ConcurrentHashMap other than it also uses hashes.
Chronicle Map is a persisted map, implementing ConcurrentMap interface, as it is said in the readme for the project.
Please do NOT use github for asking questions, stackoverflow is the Q&A platform. Github is for real issues.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Map-3.17.1](https://github.com/OpenHFT/Chronicle-Map/releases/chronicle-map-3.17.1), [BOM-2.17.196](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.196)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Map-3.17.1](https://github.com/OpenHFT/Chronicle-Map/releases/chronicle-map-3.17.1), [BOM-2.17.225](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.225)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Map-3.17.1](https://github.com/OpenHFT/Chronicle-Map/releases/chronicle-map-3.17.1), [BOM-2.17.241](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.241)
