### ISSUE TITLE
Intense CPU while reading from disk

### ISSUE THREAD

**Issue by johndavids** [OpenHFT/Chronicle-Map#179]
We are making some tests with multiple thread reads from a persisted to disk chronicle map.
When the map is in memory 100%, (due Linux file cache), the performance is as expected, similar with using a heap based map.
The first read from disk, indicated a lot of IO (around 30 GB, that was normal) and a lot of CPU. The CPU part was a little bit strange. 
We made another test, with the map only a little bit out of cache (we looked using a mincore() based tool), it read from disk only 100 MB (disk reads took just a few seconds), but the total read time was a few minutes due the very intense CPU activity. We were expecting results similar with the in-memory + IO reads time.
Any ideas why? Thank you.

**Comment by leventov** [comment]
If you open a ChronicleMap with a `createOrRecoverPersistedTo()` call, it checks the integrity of the entire map. `createPersistedTo()` should allow avoiding that.

**Comment by johndavids** [comment]
We did not open with createOrRecoverPersistedTo(). And between tests, the map stayed open.

**Comment by johndavids** [comment]
One more detail. We were reading from around 20 threads from 2 opened ChronicleMap instances (each with it's own file). One one was a little bit out of the file cache (around 100 MB). All tests, read the same keys each time.

**Comment by jackmalkovick** [comment]
We investigated and it was because of serialization, we tried using FST instead of the default and worked a little bit better. It's a little bit strange that when the map was in the file cache, even the default works very fast. It still deserializes (even if it's memory access) right?

**Comment by dpisklov** [comment]
@jackmalkovick yes, because it's an offheap memory. You can't access objects outside of Java heap without deserializing them and putting them on the heap first.
PS I assume this issue can now be closed, feel free to reopen if you disagree
