### ISSUE TITLE
Seeing significant performance slowdown with very large maps

### ISSUE THREAD

**Issue by totalslacker** [OpenHFT/Chronicle-Map#185]
I'm not sure what the theoretical upper limit is with ChronicleMap?

The key we are using is a LongValue and the value is a struct of two ints and a long. With allocating and filling a map with a few million entries we seem to get good performance. However, when I bring the size up to something closer to what we need in production (3 billion entries) we are seeing a performance slowdown of about 100x. 

The machine this is running on has 16 cpu cores and 256 GB of ram, storage for the map is a high performance NVMe SSD.

Are we expecting unreasonable things here, or might I just have a bug in my code?

**Comment by RobAustin** [comment]
In the map builder, try varying the number of entries you have set in the builder. Then re-test each time you change it. As this will effect performance, on a put(k,v) if the map gets too full it will start to take time to find an empty slot and on a get(k) it will have to scan more entries when it is full - We use the open addressing algorithm https://en.wikipedia.org/wiki/Open_addressing <https://en.wikipedia.org/wiki/Open_addressing>. So having some degree of emptiness in the map can give you better performance as log as the page cache is able to hold all the memory mappings you have open. 

Could you email us at sales@chronicle.software <mailto:sale@chronicle.software> and tell us which company you work for, we offer a commercial consulting service and in most cases we can guarantee to help you improve your performance.

**Comment by totalslacker** [comment]
I will send an email to sales shortly. In the meantime, I tried a test of inserting and getting about 26 million key/values across a range of map sizes, trying both ram only and persisted maps. This is on a 24 core machine with 384GB RAM that is otherwise idle. Disk storage was EBS (in AWS). The outcome is:


```
Max Entries    Persistent    Actual Entries   Avg PUT (mS)    Avg GET (mS)
25,000,000       FALSE         26,096,562      0.0006896       0.0001113
50,000,000       FALSE         26,096,562      0.0006898       0.0001086
500,000,000      FALSE         26,096,562      0.0008464       0.0001079
1,000,000,000    FALSE         26,096,562      0.0008922       0.0001061
25,000,000       TRUE          26,096,562      0.0010842       0.0001244
50,000,000       TRUE          26,096,562      0.0009969       0.0001256
500,000,000      TRUE          26,096,562      0.0014074       0.0001399
1,000,000,000    TRUE          26,096,562      0.0015089       0.0001248
```

Get times seem to be fairly consistent but put times increase with map size. This would make more sense to me in the persisted case given that the OS might be paging from disk. But for a pre-allocated RAM map should this be expected?

The key is a LongValue, the entry an interface of two ints and one long. I'm following the pattern of pre-allocating a key and value object for re-use during the whole process to minimize garbage.

Is this to be expected?

Thank you!

**Comment by RobAustin** [comment]
I'll get back to you regarding your question about the none persisted map. I suggest you rerun your tests with the number of entries closer to the 3 billion that you have in production, rather than the 26 million you have in your test above. In addition, when running the test I suggest you monitor the page cache hit/misses to see if there is a correlation with your slow down.

On a side note, we have another product called the market data distributor,  it is also an off-heap hash map that works between processes on the same machine. It offers better read/write latencies for highly contended keys, such as with financial market data where you are often reading and writing to the same keys at the same time, using different threads or even processes. It is unlikely to make much difference to your map because you have a huge number of keys so are unlikely to experience much contention. However, if it is of use in other areas of your project, please contact sales@chronicle.software and we can get you access to a demo version of the market data distributor.

**Comment by totalslacker** [comment]
OK thank you! I the case above I had set the map size to the value in the "Max Entries" column, then just loaded 26 million for testing (loading 3.5 billion takes close to two hours). I did, however, do the full load last night (on a non-perisisted map) with map set to the 4 billion entries. The average put time was 0.0010381 mS and the get was 0.0001057 mS (so it was slightly slower than the 0.0009755 mS put time I was getting for the 4 billion entry map with 26 million inserts).

**Comment by egalpin** [comment]
Super late to the game here haha, but @totalslacker any chance you still have the benchmarking code that you were using to compute the above tables you shared? I’m trying to evaluate ChronicleMap for a use-case I have but in benchmarks I can’t even get beyond maps with 250M entries (or more specifically, maps with on-disk size > 8 GiB)

**Comment by JerryShea** [comment]
@egalpin can you give more details "I can’t even get beyond maps with 250M entries"? Do you see an exception?
Chronicle Map has been successfully used with billions of entries.

**Comment by egalpin** [comment]
@JerryShea good call, I can add more detail. I’m trying to evaluate whether ChronicleMap could be used in a case where I would like to offload a lot of data from memory, not just from JVM heap. So I’m working with persisted maps. The map consists of a LongValue key and LongValue value, both being reused during my benchmarking as recommended. 

What I’ve noted is that the moment the persisted map requires more than 8 GiB of disk, `put` takes so long that I usually just have to kill the benchmark (JMH); it’s on the order of tens of minutes before I kill it without any confirmed writes. If I go ever so slightly below 8 GiB on-disk size, I can see that writes take place very quickly (0.5-1.0 microseconds).

**Comment by egalpin** [comment]
Just over 8 GiB is the resulting on-disk size when I set a value near `.entries(250_000_000)`

**Comment by JerryShea** [comment]
@egalpin Chronicle Map definitely works fine for this size of Map, and is being used in production. Maybe you are running into some limits on your machine? We don't have enough bandwidth to be able to help with these kind of questions - you could try asking on stackoverflow, or else have a look at https://chronicle.software/support/
