### ISSUE TITLE
Entries not appearing in map.

### ISSUE THREAD

**Issue by jhgc165** [OpenHFT/Chronicle-Map#187]
I am learning to use Chronicle-Map and I have encountered behavior that I cannot explain. 

When I try to 'put' into the map with multiple threads on the same JVM concurrently, if I use more than 11 threads, not all the entries are placed into the map (and I do not receive any errors). I have summarized the behavior in the following table:

| # of Threads | # of entries 'put' per Thread  | Expected # of Entries | Actual # of Entries |
|--------------|--------------------------------|-----------------------|---------------------|
| 1            | 1000                           | 1000                  | 1000                |
| 2            | 1000                           | 2000                  | 2000                |
| 3            | 1000                           | 3000                  | 3000                |
| 4            | 1000                           | 4000                  | 4000                |
| 5            | 1000                           | 5000                  | 5000                |
| 6            | 1000                           | 6000                  | 6000                |
| 7            | 1000                           | 7000                  | 7000                |
| 8            | 1000                           | 8000                  | 8000                |
| 9            | 1000                           | 9000                  | 9000                |
| 10           | 1000                           | 10000                 | 10000               |
| 11           | 1000                           | 11000                 | 11000               |
| 12           | 1000                           | 12000                 | 11900               |
| 13           | 1000                           | 13000                 | 12800               |
| 14           | 1000                           | 14000                 | 13700               |

If someone can help me explain this behavior (and how to go about fixing it) that would be fantastic.

Here is the code I am using and how to run it: 

**Usage:**

 _java -jar ChronicleWriteThreaded.jar {numberOfThreads} {numberOfEntriesWrittenByEachThread} {nameOfThreads}_

For example, to produce 10,000 entries in the map you can do:

```bash
$ java -jar ChronicleWriteThreaded.jar 10 1000 a
``` 
This would produce an output of: 
```bash
Running: a0
Running: a1
Running: a2
Running: a3
Running: a4
Running: a5
Running: a6
Running: a7
Running: a8
Running: a9
Finished: a7 Last written value: a7999
Finished: a9 Last written value: a9999
Finished: a8 Last written value: a8999
Finished: a4 Last written value: a4999
Finished: a0 Last written value: a0999
Finished: a3 Last written value: a3999
Finished: a2 Last written value: a2999
Finished: a5 Last written value: a5999
Finished: a6 Last written value: a6999
Finished: a1 Last written value: a1999
Number of Entries: 10000
``` 
**Code:**

```java

import java.io.File;
import java.util.Random;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

import net.openhft.chronicle.core.values.IntValue;
import net.openhft.chronicle.map.ChronicleMap;
import net.openhft.chronicle.values.Values;

public class ChronicleWriteThreaded {

    public static void main(String[] args) {

        File file = new File("/mnt/drive/chronicle");

        ChronicleMap < String, IntValue > numbers;

        try {

            numbers = ChronicleMap
                .of(String.class, IntValue.class)
                .name("DMap")
                .entries(5000000)
                .averageKey("testingverylarge")
                .createOrRecoverPersistedTo(file);

            int numberOfThreads = Integer.parseInt(args[0]);
            int numberOfItems = Integer.parseInt(args[1]);
            String threadGroupName = args[2];

            CountDownLatch latch = new CountDownLatch(numberOfThreads);


            ExecutorService executorService = Executors.newFixedThreadPool(numberOfThreads);

            for (int i = 0; i < numberOfThreads; i++) {
                executorService.submit(createTask(numberOfItems, numbers, threadGroupName + i, latch));
            }

            latch.await();
            executorService.shutdown();

            System.out.print("Number of Entries: ");
            System.out.println(numbers.size());

            numbers.close();

        } catch (Exception e) {
            System.out.println(e);
        }

    }


    private static Runnable createTask(int numberOfItems, ChronicleMap < String, IntValue > numbers, String threadGroupName, CountDownLatch latch) {

        IntValue value = Values.newHeapInstance(IntValue.class);
        Random rand = new Random();
        System.out.print("Running: ");
        System.out.println(threadGroupName);

        Runnable task = () - > {

            try {
                String store = "never done";

                for (int i = 0; i < numberOfItems; i++) {

                    value.setValue(rand.nextInt(1000000));
                    numbers.put(threadGroupName + i, value);
                    store = threadGroupName + String.valueOf(i);

                }
                System.out.print("Finished: ");
                System.out.print(threadGroupName);
                System.out.print(" Last written value: ");
                System.out.println(store);
                latch.countDown();
            } catch (Exception e) {
                System.out.println(e);
            }
        };

        return task;

    }

}

```

**Comment by RobAustin** [comment]
Are you using the latest version of chronicle-map

**Comment by jhgc165** [comment]
Yes, I am using version 3.17.3. 

```yml
<groupId>net.openhft</groupId>
<artifactId>chronicle-map</artifactId>
<version>3.17.3</version>

**Comment by dpisklov** [comment]
You have threadgroupname+i code twice - been you created a thread and then
when you create a key to put value. Let's call those i1 and i2.
So, when your i1=1 and other i2=11 (and other variations, but it obviously
starts as soon as you go to 11 and above) you have key equal to the key of
i1=11 and i2=1, and that's XXX111 where XXX is a thread group name, which
means the entry is indeed placed into the map, but at the same key.
