### ISSUE TITLE
UDP_REPLICATION_MODIFICATION_ITERATOR_ID = -128 cause IndexOutOfBoundsException

### ISSUE THREAD

**Issue by wenerme** [OpenHFT/Chronicle-Map#19]
In `ChronicleMapBuilder` `UDP_REPLICATION_MODIFICATION_ITERATOR_ID = (byte) 128`,which means `UDP_REPLICATION_MODIFICATION_ITERATOR_ID=-128`,will cause `IndexOutOfBoundsException` at    
`ReplicatedChronicleMap`
```
ModificationIterator modificationIterator = modificationIterators.get(remoteIdentifier);
```

**Comment by BoundedBuffer** [comment]
Thanks -  that bug has been fixed in the latest snapshot. So will be in the next release

Thanks again.

Rob
