### ISSUE TITLE
Outdated data access documentation

### ISSUE THREAD

**Issue by ahornace** [OpenHFT/Chronicle-Map#190]
Hello,

https://github.com/OpenHFT/Chronicle-Map/blob/master/docs/CM_Tutorial_DataAccess.adoc refers to `HeapBytesStore#uninitialized`, `HeapBytesStore#init`, `HeapBytesStore#uninit` methods which are no longer present in `3.17.4`.

Thanks.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Map-3.22ea6](https://github.com/OpenHFT/Chronicle-Map/releases/chronicle-map-3.22ea6), [BOM-2.22ea86](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea86)
