### ISSUE TITLE
Simplified support for Marshllable and BytesMarshallable in Map

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Map#196]
Add support for generic ReaderWriters.

Next, 

- use double buffering instead of having to serialize the object twice.
- make these reader/writers the default unless overwritten.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Map-3.20.40](https://github.com/OpenHFT/Chronicle-Map/releases/chronicle-map-3.20.40), [BOM-2.20.60](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.60)
