### ISSUE TITLE
Chronicle map not persisting as many entries as it has put

### ISSUE THREAD

**Issue by gowthamgutha** [OpenHFT/Chronicle-Map#200]
I am using a persistent map and the target entries are reached (i.e target_entries * max_bloat_factor).

Whenever there is IllegalStateException due to reaching of target_entries, I am logging the error

```java
      // runs in infinite loop and different key, values are passed
        try {
            map.put(key, value);
        } catch (IllegalStateException exception) {
                  log.error("map size is {}",map.size());
       }
```
The map size is getting around 2000 with the following configs:

1. average_value_size = 1000
2. target_entries = 100
3. max.bloat.factor = 4.0
4. allow_segment_tiering = true

When the target_entries * bloat_factor (100*4) is made, it comes up to a maximum of 400 or so.

Now, the process is restarted giving the map file for recovery and the entries are about 596 or so.

Why did the map.size() is 2000 before persisting and why is it 596 after recovery? But no I see no error message that recovery has failed. Is it because there is a problem recovering or a problem persisting?

**Comment by minborg** [comment]
The actual number of entries that can be put in a map depends on several factors including how keys are hashed out on different segments, actual key/value size and many other things. Make sure there is plenty of room in your maps before putting data. If you expect 2000 entries, then make sure not to under-provision the number of entries. Relying on extra segments being allocated is not a good strategy.
