### ISSUE TITLE
msync failed: error code 5 when running on docker openjdk:8-jre-alpine

### ISSUE THREAD

**Issue by marinkobabic** [OpenHFT/Chronicle-Map#204]
[36mrto_1  |[0m java.io.IOException: msync failed: error code 5
[36mrto_1  |[0m 	at net.openhft.chronicle.hash.impl.util.jna.PosixMsync.msync(PosixMsync.java:37) ~[app.jar:?]
[36mrto_1  |[0m 	at net.openhft.chronicle.hash.impl.VanillaChronicleHash.msync(VanillaChronicleHash.java:855) ~[app.jar:?]
[36mrto_1  |[0m 	at net.openhft.chronicle.hash.impl.VanillaChronicleHash.msync(VanillaChronicleHash.java:841) ~[app.jar:?]
[36mrto_1  |[0m 	at net.openhft.chronicle.map.ChronicleMapBuilder.commitChronicleMapReady(ChronicleMapBuilder.java:465) ~[app.jar:?]
[36mrto_1  |[0m 	at net.openhft.chronicle.map.ChronicleMapBuilder.createWithNewFile(ChronicleMapBuilder.java:1818) ~[app.jar:?]
[36mrto_1  |[0m 	at net.openhft.chronicle.map.ChronicleMapBuilder.createWithFile(ChronicleMapBuilder.java:1721) ~[app.jar:?]
[36mrto_1  |[0m 	at net.openhft.chronicle.map.ChronicleMapBuilder.createPersistedTo(ChronicleMapBuilder.java:1615) ~[app.jar:?]
[36mrto_1  |[0m 	at net.openhft.chronicle.map.ChronicleMapBuilder.createOrRecoverPersistedTo(ChronicleMapBuilder.java:1637) ~[app.jar:?]
[36mrto_1  |[0m 	at net.openhft.chronicle.map.ChronicleMapBuilder.createOrRecoverPersistedTo(ChronicleMapBuilder.java:1626) ~[app.jar:?]
[36mrto_1  |[0m 	at com.regtech.rto.sanction.importer.worldcheck.WorldCheckDataWriter.createVersionMap(WorldCheckDataWriter.java:46) ~[app.jar:?]
[36mrto_1  |[0m 	at com.regtech.rto.sanction.importer.worldcheck.WorldCheckDataWriter.init(WorldCheckDataWriter.java:53) ~[app.jar:?]
[36mrto_1  |[0m 	at com.regtech.rto.sanction.importer.worldcheck.WorldCheckDataWriter.add(WorldCheckDataWriter.java:68) ~[app.jar:?]
[36mrto_1  |[0m 	at com.regtech.rto.sanction.importer.worldcheck.WorldCheckImporter.execute(WorldCheckImporter.java:127) ~[app.jar:?]
[36mrto_1  |[0m 	at com.regtech.rto.sanction.verticles.AbstractImportVerticle.executeImport(AbstractImportVerticle.java:104) ~[app.jar:?]
[36mrto_1  |[0m 	at com.regtech.rto.sanction.verticles.AbstractImportVerticle.executeImportIfFileIsReady(AbstractImportVerticle.java:68) ~[app.jar:?]
[36mrto_1  |[0m 	at com.regtech.rto.sanction.verticles.AbstractImportVerticle.executeImportIfFileIsReady(AbstractImportVerticle.java:96) ~[app.jar:?]
[36mrto_1  |[0m 	at com.regtech.rto.sanction.verticles.AbstractImportVerticle.lambda$null$2(AbstractImportVerticle.java:167) ~[app.jar:?]
[36mrto_1  |[0m 	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316) ~[app.jar:?]
[36mrto_1  |[0m 	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76) ~[app.jar:?]
[36mrto_1  |[0m 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
[36mrto_1  |[0m 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
[36mrto_1  |[0m 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [app.jar:?]

**Comment by dpisklov** [comment]
@marinkobabic when using docker you must ensure you use --ipc="host" and we only tested putting files on the bind-mounted folders from the host (i.e. -v /host/dir/1/:/container/dir ). Please try this and let us know.

**Comment by marinkobabic** [comment]
@dpisklov I tried host, shared, private and none of them worked. Any idea? If you wan't me I can prepare a example for your. I use docker-compose in my tests.

`version: '3.7'
services:
  rto:
    image: "regtechone/rto:latest"
    ports:
      - "8080:8080"
    volumes:
      - C:/temp/mytest/data:/data:rw
      - C:/temp/mytest/import:/import
    ipc: host

`

**Comment by dpisklov** [comment]
@marinkobabic are you able to test on Linux?
None of us ever used/tested it on Windows, so it might well be a Windows-specific issue which we can't really test...

**Comment by marinkobabic** [comment]
Can do the check also by running docker on Linux. Will let you know how it
goes.

**Comment by marinkobabic** [comment]
On Linux the same code works fine by using the ipc:host

Any way to get it running on Windows docker as well?

**Comment by dpisklov** [comment]
It's the question for docker I'm afraid...

>

**Comment by minborg** [comment]
I will close this issue @marinkobabic . Please reopen if your Windows Docker issues persist on newer versions.
