### ISSUE TITLE
How to open an existing chronicleMao database 

### ISSUE THREAD

**Issue by ypriverol** [OpenHFT/Chronicle-Map#208]
Hi: 
I haven't been able to find an example code showing how to load into memory an existing chroniclemap database. Is that possible?

Thanks in advance

**Comment by dpisklov** [comment]
See [here](https://github.com/OpenHFT/Chronicle-Map/blob/master/docs/CM_Tutorial.adoc#persisted-chronicle-map)
Please use stackoverflow for questions
