### ISSUE TITLE
Auto resize is zero upon a restart of replicated map

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Map#214]
We had the following issue reported - Auto resize is zero upon a restart of replicated map

The following test passes, so awaiting feedback from the client:

```
net.openhft.chronicle.map.AutoResizeTest
```

**Comment by minborg** [comment]
Can we close this issue @RobAustin as we now have a test for it?

**Comment by RobAustin** [comment]
Closing as we received no further feedback from the client - and we now have the AutoResizeTest
