### ISSUE TITLE
Cleaned up shutdown code so exceptions where not logged during shutdown

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Map#219]
An exception was being logged from OldDeletedEntriesCleanupThread during a shutdown

**Comment by hft-team-city** [comment]
Released in [Chronicle-Map-3.19.30](https://github.com/OpenHFT/Chronicle-Map/releases/chronicle-map-3.19.30), [BOM-2.19.176](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.19.176)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Map-3.19.30](https://github.com/OpenHFT/Chronicle-Map/releases/chronicle-map-3.19.30), [BOM-2.19.179](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.19.179)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Map-3.19.30](https://github.com/OpenHFT/Chronicle-Map/releases/chronicle-map-3.19.30), [BOM-2.19.180](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.19.180)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Map-3.19.30](https://github.com/OpenHFT/Chronicle-Map/releases/chronicle-map-3.19.30), [BOM-2.19.181](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.19.181)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Map-3.19.30](https://github.com/OpenHFT/Chronicle-Map/releases/chronicle-map-3.19.30), [BOM-2.19.182](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.19.182)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Map-3.19.30](https://github.com/OpenHFT/Chronicle-Map/releases/chronicle-map-3.19.30), [BOM-2.19.184](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.19.184)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Map-3.19.30](https://github.com/OpenHFT/Chronicle-Map/releases/chronicle-map-3.19.30), [BOM-2.19.185](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.19.185)
