### ISSUE TITLE
Compile error if replace com.intellij:annotations with org.jetbrains:annotation

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Map#222]
`[ERROR] /home/teamcity/agents/dev11b/work/39269a5b52212c57/target/generated-sources/annotations/net/openhft/chronicle/map/impl/CompiledMapQueryContext.java:[21,35] <identifier> expected`

Not at all clear why this happens

**Comment by JerryShea** [comment]
Related to https://github.com/OpenHFT/Stage-Compiler/issues/1 ?

**Comment by minborg** [comment]
Yes @JerryShea . Probably related. Now that we do not use the annotation processor, this problem might have gone. I will have a look.

**Comment by tgd** [comment]
Closing this out as no work is planned on this at the moment. Please comment on this issue if you would like it re-opened. If you would like to expedite the development of this please get in touch with us here for commercial support: https://chronicle.software/contact-us/
