### ISSUE TITLE
Having issue with List of maps

### ISSUE THREAD

**Issue by itdeepdive** [OpenHFT/Chronicle-Map#223]
List<Map<String, Object>> dataMap = rows i fetch from db.....;

i want to store this dataMap in to persisted chroniclemap in a .dat file. is this supported in Chronicle-Map.

**Comment by dpisklov** [comment]
It's not clear what you want to do with Chronicle Map. You can read documentation to understand more about what Chronicle Map can and can not do. 
Github is for real issues you have with code, for questions there's stackoverflow.
