### ISSUE TITLE
how can i check the "nio.directbuffer.used" ?

### ISSUE THREAD

**Issue by hbsuper007** [OpenHFT/Chronicle-Map#227]
how can i check the amount of  memory that chronicle-map allocates？
i know that "map.offHeapMemoryUsed()" works, but i want to get the info from system scope.

i checked "jvm.nio.directbuffer.used",but it seems no larger.so Chronicle-Map is not based on nio's directbuffer?

**Comment by minborg** [comment]
Chronicle Map is using 64-bit memory mapping for persisted maps. 

Here is a thread on off-heap memory usage: https://stackoverflow.com/questions/16697135/monitor-non-heap-memory-usage-of-a-jvm
