### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by robertoandrade** [OpenHFT/Chronicle-Map#23]
I was trying to include this dependency on one of my Android projects and noticed the DEX process complains about one of the transient dependencies (`stax`) given that Android doesn't allow `java.*` and `javax.*` classes to be packaged in an APK/DEX file.

I was wondering if you guys had ever tested the implementation of the Map in an Android environment and if it's a supported use case or if there was any plans for it? I'm testing just excluding that transient dependency for right now to be able to at least pass the packaging phase and test the implementation on a device to see what else pops up.

**Comment by peter-lawrey** [comment]
Hello Roberto,
Using Map on Android would be very interesting.  It's something we would
like to explore but we don't have the resources at the moment.

Regards,
   Peter.
