### ISSUE TITLE
Unmonitor the segmentBytes in a Map's QueryContext

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Map#232]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Map-3.20.61](https://github.com/OpenHFT/Chronicle-Map/releases/chronicle-map-3.20.61), [BOM-2.20.84](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.84)
