### ISSUE TITLE
Size of map on disk

### ISSUE THREAD

**Issue by gary-distinctive** [OpenHFT/Chronicle-Map#237]
Can you help me understand why the ChronicleMap .dat file created by this configuration differs in size between Windows and Linux please?

We are using ChronicleMap version 3.20.40

val mapBuilder = ChronicleMapBuilder
                .of(String::class.java, StorePayload::class.java)
                .name(cacheName)
                .actualSegments(Runtime.getRuntime().availableProcessors() * 2)
                .averageKeySize(8.0)
                .averageValueSize(200.0)
                .entries(10_000_000L)

Windows file size ~3.2Gb
Linux file size ~269Gb

-rw-r--r--. 1 xxx xxx 269454475264 Oct 21 19:03 edc933af-dbc4-4158-b608-351b38cfdef5.dat

**Comment by minborg** [comment]
If you type the following LInux command:

```
du -h  edc933af-dbc4-4158-b608-351b38cfdef5.dat
```

What do you see?

**Comment by gary-distinctive** [comment]
$ ls -la
-rw-r--r--. 1 xxx xxx 269454475264 Oct 23 12:48 66b61298-84ad-4b5c-a94a-4b594fb5d8de.dat
$ du -h 66b61298-84ad-4b5c-a94a-4b594fb5d8de.dat
251G    66b61298-84ad-4b5c-a94a-4b594fb5d8de.dat

**Comment by RobAustin** [comment]
@gary-distinctive why did you close this, did you find the reason for the discrepancy in the sizes? [ as we were just starting to investigate this ]

**Comment by gary-distinctive** [comment]
Hi Rob - yes, root cause was local coding issue

**Comment by hft-team-city** [comment]
Released in [Chronicle-Map-3.20.84](https://github.com/OpenHFT/Chronicle-Map/releases/chronicle-map-3.20.84), [BOM-2.20.192](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.192)
