### ISSUE TITLE
ChronicleSet is not thread safe

### ISSUE THREAD

**Issue by rsmilyanov** [OpenHFT/Chronicle-Map#24]
Hello,

I am running some tests for ChronicleSet of strings that is supposed to be used concurrent by 5 threads and with the following code I am getting "net.openhft.chronicle.hash.locks.IllegalInterProcessLockStateException: Must not acquire update lock, while read lock is already held by this thread"

Here the code snippet:

public class TestChronicleSet {

    public static <H extends ChronicleHash<K,?>,  B extends ChronicleHashBuilder<K, H, B>, K> H init(B builder, int entrySize, int averageKeySize, String fileName) {

        String tmp = System.getProperty("java.io.tmpdir");
        String pathname = tmp + "/" + fileName;
        File file = new File(pathname);
        try {
            H result = builder.entries(entrySize).averageKeySize(averageKeySize).createPersistedTo(file);
            return result;
        } catch (IOException ioe) {
            throw new RuntimeException(ioe);
        }
    }

    public synchronized static <A> ChronicleSet<A> initSet(Class<A> entryClass, int entrySize, int averageKeySize, String fileName) {
        return init(ChronicleSetBuilder.of(entryClass), entrySize, averageKeySize, fileName);
    }

    public static void main(String[] args) {
        ChronicleSet<String> set = initSet(String.class, 1_000_000, 30, "stringSet.dat");
        ExecutorService executor = Executors.newFixedThreadPool(5);
        for (int i = 0; i < 10; i++) {
            Runnable worker = new WorkerThread(set);
            executor.execute(worker);
        }
        executor.shutdown();
        while (!executor.isTerminated()) {

        }
        System.out.println("Finished all threads");

    }

    public static class WorkerThread implements Runnable {
        private final ChronicleSet<String> set;
        public WorkerThread(ChronicleSet<String> set){
            this.set = set;
        }

        @Override
        public void run() {
            System.out.println(Thread.currentThread().getName()+" Start. Command = " + set.size());
            processCommand();
            System.out.println(Thread.currentThread().getName()+" End.");
        }

        private void processCommand() {
            Set<String> nomenclatures = new HashSet<>();
            for(int i = 0; i < 10; i++) {
                String nomenclature = "#############################" + i;
                nomenclatures.add(nomenclature);

            }

            set.addAll(nomenclatures);

            Set<String> strings = CollectionUtil.randomSubset(nomenclatures, new Random());

            set.addAll(strings);

            Set<String> toRemove = new HashSet<>();
            Random generator = new Random();
            for (int j = 0; j < 3; j++) {
                int i = generator.nextInt(10);
                String nomenclature = "#############################" + i;
                toRemove.add(nomenclature);
            }
            set.removeAll(toRemove);

            for (String s : set) {
                System.out.println(s);
            }

            strings = CollectionUtil.randomSubset(nomenclatures, new Random());

            set.addAll(strings);

            for (String s : set) {
                System.out.println(s);
            }
        }

    }
}

Since ChronicleSet is almost the same as ChronicleMap I expect that it will be thread safe. Can you please have a look at the example code and let me know whether it is a bug into ChronicleSet implementation or I am supposed to synchronize the code for addAll/removeAll operations on the application side?

Thanks,
Radoslav

**Comment by BoundedBuffer** [comment]
Thanks for your email, before we look into this, can you tell me which version  you  are using ?

**Comment by rsmilyanov** [comment]
I am using 3.0.2-alpha version.

**Comment by BoundedBuffer** [comment]
Thank you for the version, we will look into the issue, for now I suggest you don’t use an Alpha version, could you retry with chronicle-map 2.1.8

**Comment by rsmilyanov** [comment]
Hi,

I just tried it with version 2.1.8 with the same code and I am getting:

Exception in thread "pool-1-thread-2" java.util.NoSuchElementException
	at net.openhft.chronicle.map.VanillaChronicleMap$EntryIterator.next(VanillaChronicleMap.java:2556)
	at net.openhft.chronicle.map.VanillaChronicleMap$EntryIterator.next(VanillaChronicleMap.java:2514)
	at java.util.AbstractMap$1$1.next(AbstractMap.java:339)
	at TestChronicleSet$WorkerThread.processCommand(TestChronicleSet.java:102)
	at TestChronicleSet$WorkerThread.run(TestChronicleSet.java:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by bobymicroby** [comment]
@BoundedBuffer  Hello Rob, 
Can you please direct me to a part of the documentation about the concurrency guarantees of ChronicleMap ? 
Regards, B.

**Comment by BoundedBuffer** [comment]
thanks

**Comment by BoundedBuffer** [comment]
ok but thats a different error than

net.openhft.chronicle.hash.locks.IllegalInterProcessLockStateException:

**Comment by rsmilyanov** [comment]
Yes, that's right. Nevertheless the original exception is being replaced by a new one :)
Again it seems that it's not thread safe because one of the element that is being removed is already removed by some other thread.

**Comment by BoundedBuffer** [comment]
Chronicle Map uses ReentrantLocks and segment looking to avoid locking contention. 

see also 

https://github.com/OpenHFT/Chronicle-Map#off-heap-storage-and-how-using-a-proxy-object-can-improve-performance

**Comment by BoundedBuffer** [comment]
I’ve raised the following JIRA

https://higherfrequencytrading.atlassian.net/secure/RapidBoard.jspa?rapidView=11&view=detail&selectedIssue=HCOLL-339 <https://higherfrequencytrading.atlassian.net/secure/RapidBoard.jspa?rapidView=11&view=detail&selectedIssue=HCOLL-339>

Rob

**Comment by rsmilyanov** [comment]
Yes, that's the interface for ChronicleMap, but if I am using the intefrace for ChronicleSet I do not have these APIs. Am I supposed to switch the implementation to ChronicleMap?

**Comment by BoundedBuffer** [comment]
Yes, the set implementation is just a wrapper around the map, so you maybe better off using the map directly.

**Comment by bobymicroby** [comment]
@BoundedBuffer There is a method getUsingLocked that read locks the map segment but as far as I see there is no put method that write locks the maps segment ?  The concurrency part of documentation is lacking semantic details . Simple examples for MPSC , SPMC, SPSC cases will be very helpful as well. After all this is one of the most import aspects of libraries of such kind.

**Comment by BoundedBuffer** [comment]
the put() method locks the maps segment, but it does not hold the lock until the end of the context scope. If this is what you want then use 
acquireUsingLocked()


see https://github.com/OpenHFT/Chronicle-Map#acquireusinglocked


regarding 
>Simple examples for MPSC , SPMC, SPSC cases will be very helpful as well.
I’ve raised the following JIRA - https://higherfrequencytrading.atlassian.net/browse/HCOLL-341 <https://higherfrequencytrading.atlassian.net/browse/HCOLL-341>

If you want to help us with this documentation we can accept your pull requests ,  we can help by answering any question that you have.


Rob

**Comment by bobymicroby** [comment]
@BoundedBuffer 

Hi Rob, can I safely guess that the context scope of a put method is the put method itself. And that the put method is atomic and thread-safe ? 

Can you please elaborate more on 

>the put() method locks the maps segment, but it does not hold the lock until the end of the context scope. 

As far as I can see acquireUsingLocked creates a default value if the key is absent and accepts a instance  of the Value class that will be populated with either the default value for that map or with the existing value behind the key.  

So I hope that I don't have to do something like 
```java
final Value v = new  Value() 

try( Context c = map.acquireUsingLocked(non_existing_key,v)) {
v.a = 1

} /**  Here 1 should be atomically inserted into the map ?*/

try( Context c = map.acquireUsingLocked(non_existing_key,v)) {
v.a = 2

} /**  Here 2 should be atomically inserted into the map ?*/

```

Some of methods provide you with a Context directly and other like put doesn't. This is adding a bit of confusion .

**Comment by BoundedBuffer** [comment]
> On 29 May 2015, at 14:09, Borislav Ivanov <notifications@github.com> wrote:
> 
> @BoundedBuffer <https://github.com/BoundedBuffer>
> Hi Rob, can I safely guess that the context scope of a put method is the put method itself. And that the put method is atomic and thread-safe ?
> 
>Yes to both

> Can you please elaborate more on
> 
> the put() method locks the maps segment, but it does not hold the lock until the end of the context scope.
> 
the put method holds a lock, once the put() has completed the lock is released.


> As far as I can see acquireUsingLocked creates a default value if the key is absent and accepts a instance of the Value class that will be populated with either the default value for that map or with the existing value behind the key.
> 
yes


Its probably best to illustrate this with examples see out test cases at ( see net.openhft.chronicle.map.CHMUseCasesTest) 

here is once such test case that you may find useful.

public void testAcquireUsingWithCharSequence() throws IOException {

    if (typeOfMap == TypeOfMap.STATELESS)
        return; // getUsingLocked supported by the STATELESS client


    ChronicleMapBuilder<CharSequence, CharSequence> builder = ChronicleMapBuilder
            .of(CharSequence.class, CharSequence.class);

    try (ChronicleMap<CharSequence, CharSequence> map = newInstance(builder)) {

        CharSequence using = map.newValueInstance();

        try (WriteContext wc = map.acquireUsingLocked(“1”, using)) { // write lock() on the segment
            assertTrue(using instanceof StringBuilder);
            ((StringBuilder) using).append("Hello World");
        }  // write locked released

        assertEquals("Hello World", map.get("1"));
        mapChecks();
    }
}

**Comment by bobymicroby** [comment]
@BoundedBuffer 
So this 
-------
``` java
    try (WriteContext wc = map.acquireUsingLocked(“1”, using)) { // write lock() on the segment
            assertTrue(using instanceof StringBuilder);
            ((StringBuilder) using).append("Hello World");
        } 
```
is equivalent to  

```java
map.put("1","Hello World") 
```
 
in concurrency terms ? 


I will have a look at the tests.
Thanks a lot for the info.

**Comment by BoundedBuffer** [comment]
yes - in concurrency terms

**Comment by bobymicroby** [comment]
Great :) Thanks again.

**Comment by leventov** [comment]
@bobymicroby Please check the test checked into the repo by commit 7ec4882d565c5b946e83637bd24c8ae0de987ea0 . Does it correctly reflects your own test? I haven't found CollectionUtil.randomSubset on a public library, used somewhat similar functionality from some random library/

This test passes on my dev machine (4-core) without exceptions, using ChronicleMap 2.1 branch HEAD.

**Comment by bobymicroby** [comment]
@leventov  Things looks good , thanks a lot. I will double-check with @rsmilyanov when he comes back from holidays in Wednesday and will write a follow up.

**Comment by rsmilyanov** [comment]
@leventov I can confirm that test is passing successfully on version 2.1.8 but the problem remains with 3.0.2alpha version. I am running the test which you have created on 2.1 branch locally on ubuntu OS with kernel version 3.13.0-53-generic. And the exception occurs each time on my machine.

**Comment by BoundedBuffer** [comment]
thanks for this information - please note, the 3.0.2 alpha ( being an alpha version ) is still very much work in progress, but thanks again, any bug report feedback is always welcome.
