### ISSUE TITLE
www.google-analytics.com

### ISSUE THREAD

**Issue by danjmarques** [OpenHFT/Chronicle-Map#247]
Is seems that 3.20.84 (but not any of the versions I used before) is attempt to connect with www.google-analytics.com?

Why is this?  Is this by design in the Chronicle-Map code, or is that something that snuck in via a dependency?  If the former, is there a way to disable this?  We won't be able to use this software as it will trigger a security alert.

In either case, this is a bit worrisome

**Comment by minborg** [comment]
Hi @danjmarques and thank you for your question. 

Knowing how our products are used allows us to focus our resources more efficiently in our effort to improve our libraries and provide better and more widely adopted solutions for the open-source community as described here https://github.com/OpenHFT/Chronicle-Map/blob/master/DISCLAIMER.adoc

Data is sent via a secure connection and we disclose reports of the collected data to the general public: https://docs.google.com/spreadsheets/d/e/2PACX-1vR7SKi7gCDlo4DEQGu8ocW6-cTYL8rV5Gn7nDBPe4trdNkp5E8TAmcVAMwC4acdN9g65_N1KEuljkfD/pubhtml#

Having said this, I appreciate that there are cases when this is not acceptable. Please contact info@chronicle.software and we will promptly assist you to disable the functionality.

**Comment by danjmarques** [comment]
I really hope you reconsider this decision.

I would imagine that most places that need software "designed for low-latency, and/or multi-process applications, such as trading and financial market applications" will 

1. be running in an environment where the connection to google-analytics.com will be blocked.  The connection attempt will be detected and trigger an info-sec alert, which will result in the need to do an info-sec analysis of the software, etc.
2. be unhappy that another thread was created in their application, given that these kinds of applications usually have a finite number of threads, where the assignment of threads to cores is carefully controlled.
3. really upset to learn that "The three top-most external package names (e.g. "org.apache.commons")" will be reported, as (if I understand correctly, external to net.openhft) this will likely identify the entity use the software.

**Comment by danjmarques** [comment]
And to follow up to my earlier comment for any 3rd party: net.openhft.chroncicle.core.internal.analytics.StandardMaps.standardAdditionalEventParameters will report the user's "internal" package names (first 3 parts) as long as they are in the top 3 most frequent.  This will likely result in sending identifiable information to google-analytics.

**Comment by minborg** [comment]
Thanks again @danjmarques for your input on this. Let's take a step back and look at some facts:

* We have added analytics because we think it will improve our products and how they are used.
* It is completely voluntary to leave the feature on.
* We disclose what we do (see below).
* We make reports available to the general public.
* Analytics will send data (as disclosed) to Google Analytics via a secure connection.
* Analytics will use system resources (E.g. a background thread and a very tiny amount of memory).
* The open-source libraries are provided by Chronicle free of charge and are open to anyone to read/modify.

As a result of your comments and in an attempt to increase transparency further, we will now print out a log message with information on analytics and where to read more/turn it off starting from version 3.20.85.  I will also see if we can improve information on thread usage etc.

It is evident that you do not wish to use analytics so therefore I would recommend contacting info@chronicle.software to have it removed. It is a very simple process.

**Comment by minborg** [comment]
I have added thread usage info as per https://github.com/OpenHFT/Chronicle-Map/issues/249

**Comment by danjmarques** [comment]
@minborg - Thanks for the response.  I understand what you are trying to accomplish, but I, and most other users, I guess, would much prefer if something like this was enabled via opting in, rather than needing to contact you to opt out.  

Like I stated before, I would imagine that many (most?) of the users of such a library will be running the software in an environment where the request to google-analytics.com will be blocked, and will likely learn about this change to your software when an info-sec warning is triggered.

While a disclaimer describing this new functionality was included in the new version, this change wasn't listed in the release notes - at least  when I checked them before upgrading to 3.20.84 (and still not, as of this instant).  This means that at least a few users are going to learn about this new functionality in a rather alarming way.


![3 20 84](https://user-images.githubusercontent.com/32913166/102250199-41535780-3ed1-11eb-84ed-c4aa2bb56aa8.PNG)

**Comment by minborg** [comment]
Hi again @danjmarques 

It was not ideal that analytics was missing in the release notes as you rightfully pointed out. I have added a place holder issue (https://github.com/OpenHFT/Chronicle-Map/issues/250) so that this will be clear in the next release. 

Thanks for pointing out this!

**Comment by peter-lawrey** [comment]
Thank you for your feedback.
I can understand commercial companies finding this surprising and concerning, 
all we ask is that you let us know who you are one way or another at no cost to yourself, nothing to sign.
We need this information to get investment in maintaining these products as investors won't pay any money if we can't even say who is using our products for free. Just saying we have 20,000 downloads a month but have no idea who they just make us look like we literally don't know why we are developing these products commercially.

**Comment by peter-lawrey** [comment]
Chronicle Map is a good example, we have been talking about doing a next-generation re-write for years but can't justify the R&D this would involve, instead, all improvements have gone into commercial products like Market Data Distributor.

**Comment by edudar** [comment]
@minborg could you please clarify regarding opting-out. It seems that to remove analytics one has to contact info@. How exactly this removal process works?

I learnt about analytics simply by going through the recent commits. Was trying to learn what has changed from one version to another as release notes don't really cover that and there are lots of commits that are not associated with any issue or pull request. Marked chronicle-map as non-upgradable in my code until analytics issue is resolved.

**Comment by minborg** [comment]
@edudar The removal process is described at the end of https://github.com/OpenHFT/Chronicle-Map/blob/ea/DISCLAIMER.adoc

In short, you send an email to info@chronicle.software and you will receive instructions on how to turn it off.

As you rightly point out, there are several improvements that go into the product with no reference to a particular issue.

**Comment by jazdw** [comment]
Why the secrecy about how to turn it off? Given this is an Apache 2.0 licensed library it is surprising and concerning to see that it is collecting data in the background and sending it to a third party.

For anyone trying to turn this off, have a look at `net.openhft.chronicle.core.analytics.AnalyticsFacade#isEnabled`
Set the Java system property `chronicle.analytics.disable` to true.
