### ISSUE TITLE
SIGSEGV in Chronicle-Map 2.1.8  &  3.0.2   x86-64 on  OSX 10.10.3 & Ubuntu  with 3.13.0-53-generic 

### ISSUE THREAD

**Issue by bobymicroby** [OpenHFT/Chronicle-Map#25]
```#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000000011152b9f6, pid=82407, tid=24835
#
# JRE version: Java(TM) SE Runtime Environment (8.0_40-b25) (build 1.8.0_40-b25)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.40-b25 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# J 1429 C2 net.openhft.lang.collection.SingleThreadedDirectBitSet.setNextNContinuousClearBits(JI)J (486 bytes) @ 0x000000011152b9f6 [0x000000011152b940+0xb6]
#
```

Can be reproduced by https://gist.github.com/bobymicroby/b78cea832ba190300211

**Comment by BoundedBuffer** [comment]
thanks we have raised the following JIRA - https://higherfrequencytrading.atlassian.net/browse/HCOLL-340 <https://higherfrequencytrading.atlassian.net/browse/HCOLL-340>

**Comment by bobymicroby** [comment]
@peter-lawrey @leventov , This bug shatters the foundations of the library because it simulates the most common usage pattern - few consumers flooding the map and one consumer processing it. We are receiving various SIGSEGV not only   in setNextNContinuousClearBits but in other methods as well. After the conversation I had with @BoundedBuffer in #24  , he confirmed that put/get are atomic operations . Obviously something is terribly wrong either with the library or the way we are trying to use it. Do you have any updates on this issue ?

**Comment by BoundedBuffer** [comment]
Thank you for the bug report, we will update the JIRA once we have more information on this issue.

**Comment by leventov** [comment]
@bobymicroby seems that it was not a Chronicle Map bug, in your test case you close the map (hence  unmap off-heap memory) before the worker treads end concurrent updates to the map. We also experienced segmentation faults on our CI server with linux, but they gone after this commit: 055d1da318d5aefb0ea930895df28c7b708da92c
