### ISSUE TITLE
Deserialisation cost of using Chronicle Maps

### ISSUE THREAD

**Issue by viswanathk** [OpenHFT/Chronicle-Map#268]
Hello,

It is written in the documentation that using the `Value` interface is useful for two things:

1. No additional garbage
2. Almost negligible deserialisation cost.

Is there any documentation or explanation on why there is negligible deserialisation cost? Typically when we move things out of the Java heap, the most common concern is the SerDe cost. How is ChronicleMaps avoiding that?

It will be helpful if you can shed some light on Pt 1 as well.

**Comment by minborg** [comment]
As value objects are mutable, they can be reused. Also, some of them are specialized holding a primitive value only, which speeds up serialization.
