### ISSUE TITLE
mvn install fails on AArch64, Fedora 33 

### ISSUE THREAD

**Issue by LutzWeischerFujitsu** [OpenHFT/Chronicle-Map#270]
[jw@cn05 map]$ [jw@cn05 map]$ mvn install
[INFO] Scanning for projects...
Downloading from Snapshot Repository: https://oss.sonatype.org/content/repositories/snapshots/net/openhft/chronicle-bom/2.21ea-SNAPSHOT/maven-metadata.xml
Downloaded from Snapshot Repository: https://oss.sonatype.org/content/repositories/snapshots/net/openhft/chronicle-bom/2.21ea-SNAPSHOT/maven-metadata.xml (787 B at 139 B/s)
[INFO]
[INFO] ---------------------< net.openhft:chronicle-map >----------------------
[INFO] Building OpenHFT/Chronicle-Map 3.21ea7-SNAPSHOT
[INFO] -------------------------------[ bundle ]-------------------------------
Downloading from chronicle-enterprise-snapshots: https://nexus.chronicle.software/content/repositories/snapshots/net/openhft/chronicle-wire/2.21ea11/chronicle-wire-2.21ea11.pom
Downloading from chronicle-enterprise-release: https://nexus.chronicle.software/content/repositories/releases/net/openhft/chronicle-wire/2.21ea11/chronicle-wire-2.21ea11.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  11.087 s
[INFO] Finished at: 2021-03-03T14:12:13+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project chronicle-map: Could not resolve dependencies for project net.openhft:chronicle-map:bundle:3.21ea7-SNAPSHOT: Failed to collect dependencies at net.openhft:chronicle-wire:jar:2.21ea11: Failed to read artifact descriptor for net.openhft:chronicle-wire:jar:2.21ea11: Could not transfer artifact net.openhft:chronicle-wire:pom:2.21ea11 from/to chronicle-enterprise-snapshots (https://nexus.chronicle.software/content/repositories/snapshots): authentication failed for https://nexus.chronicle.software/content/repositories/snapshots/net/openhft/chronicle-wire/2.21ea11/chronicle-wire-2.21ea11.pom, status: 401 Unauthorized -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[jw@cn05 map]$

**Comment by JerryShea** [comment]
Hi @LutzWeischerFujitsu, I would hope that this was caused by a transient condition. Sometimes maven central takes a very long time to publish dependencies.
