### ISSUE TITLE
Illegal reflective access operation

### ISSUE THREAD

**Issue by wapgui** [OpenHFT/Chronicle-Map#271]
With all versions later 3.17.8 on Java 11 this message occurs:

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access using Lookup on net.openhft.chronicle.core.Jvm (file:/Users/TORS/.m2/repository/net/openhft/chronicle-core/2.19.32/chronicle-core-2.19.32.jar) to class java.lang.reflect.AccessibleObject
WARNING: Please consider reporting this to the maintainers of net.openhft.chronicle.core.Jvm
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by mores** [comment]
I am seeing this also using the following JVM:

openjdk version "11.0.10" 2021-01-19 LTS
OpenJDK Runtime Environment Zulu11.45+27-CA (build 11.0.10+9-LTS)
OpenJDK 64-Bit Server VM Zulu11.45+27-CA (build 11.0.10+9-LTS, mixed mode)

**Comment by justinjohnson02** [comment]
Ditto, I also see this with the latest version of Chronicle-Map ‎**3.21ea41**. I am just testing it out for possible adoption/use so I guess I'll be bumping down to version **3.17.7**.

**Comment by tuhuynh27** [comment]
Same issue faced

**Comment by BryanWang1** [comment]
Also having the exact same issue. although my line says

"WARNING: Illegal reflective access using Lookup on net.openhft.chronicle.core.Jvm (file:/C:/Users/NAME/.m2/repository/net/openhft/chronicle-core/2.21ea61/chronicle-core-2.21ea61.jar) to class java.lang.reflect.AccessibleObject"

**Comment by justinjohnson02** [comment]
I think they're aware: https://github.com/OpenHFT/Java-Runtime-Compiler/issues/63#issuecomment-860831114

**Comment by hpuac** [comment]
Also raised here: https://github.com/OpenHFT/Chronicle-Core/issues/192
We run into the same issue since we updated the JVM to version 16 and needed to add some flags to still make it work, otherwise the service would stop with an exception:
```
--add-opens java.base/java.lang.reflect=ALL-UNNAMED
--add-exports java.base/jdk.internal.ref=ALL-UNNAMED
--add-exports java.base/sun.nio.ch=ALL-UNNAMED
```

**Comment by minborg** [comment]
It would be possible to add these statements in the MANIFEST file to provide smother transition to more recent Java versions:

Two new JDK-specific JAR-file manifest attributes are defined to correspond to the --add-exports and --add-opens command-line options:
```
Add-Exports: <module>/<package>( <module>/<package>)*
Add-Opens: <module>/<package>( <module>/<package>)*
```
See https://openjdk.java.net/jeps/261#Breaking-encapsulation

**Comment by maxim5** [comment]
Same problem here (JVM 16):
```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at net.openhft.chronicle.core.Jvm.get_setAccessible0_Method(Jvm.java:225)
	at net.openhft.chronicle.core.Jvm.<clinit>(Jvm.java:134)
	at net.openhft.chronicle.map.ChronicleMapBuilder.<clinit>(ChronicleMapBuilder.java:166)
	at net.openhft.chronicle.map.ChronicleMap.of(ChronicleMap.java:72)
	at com.github.maxim5.snippets.db.chronicle.TryChronicleMap.main(TryChronicleMap.java:11)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.openhft.chronicle.core.Jvm.get_setAccessible0_Method(Jvm.java:222)
	... 4 more
Caused by: java.lang.IllegalAccessException: module java.base does not open java.lang.reflect to unnamed module @445b84c0
	at java.base/java.lang.invoke.MethodHandles.privateLookupIn(MethodHandles.java:260)
	... 9 more
```

**Comment by jazdw** [comment]
Any progress on this with the release of Java 17 LTS today?

**Comment by justinjohnson02** [comment]
I think it would help to know where on the roadmap Java 17 support is.

**Comment by RobAustin** [comment]
We are hoping to get most of our projects to support java 17 this year.

**Comment by justinjohnson02** [comment]
> We are hoping to get most of our projects to support java 17 this year.

Thanks for the update @RobAustin ! 😄

**Comment by minborg** [comment]
Please read more on the issue here: https://chronicle.software/chronicle-support-java-17/

I am closing this issue now. Please reopen if appropriate.
