### ISSUE TITLE
maven dependency problem

### ISSUE THREAD

**Issue by sunqinwpu** [OpenHFT/Chronicle-Map#28]
<dependency>
                <groupId>net.openhft</groupId>
                <artifactId>chronicle-bom</artifactId>
                <type>pom</type>
                <version>1.0.9-SNAPSHOT</version>
                <scope>import</scope>
            </dependency>

this dependency does not exist in maven central repository? why?

**Comment by sunqinwpu** [comment]
i am using github trunk. 
when i execute mvn eclipse:eclipse, it encount the error.

**Comment by BoundedBuffer** [comment]
It's a snapshot dependency so will be in the snapshot repo

    <repository>
            <id>Snapshot Repository</id>
            <name>Snapshot Repository</name>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
