### ISSUE TITLE
Make jetbrains annotations dependencies as provided?

### ISSUE THREAD

**Issue by ahornace** [OpenHFT/Chronicle-Map#289]
Hello,

we are using your library but unfortunately it brings jetbrains annotations with versions 12 and 19 as its dependencies whereas we use the newest version 21. We chose to exclude the annotations library in maven when adding chronicle-map, however, the Tomcat jar scanning still complains.

Do you think it would make sense to mark the library as `provided` (compile only)? The annotations themselves should not be required as a regular dependency since they mostly should be used by IDE and their `RetentionPolicy` is `CLASS` so they shouldn't be used by reflection. Furthermore, even official github page marks them as `provided`: https://github.com/JetBrains/java-annotations

Thanks!

**Comment by minborg** [comment]
As a side note, we are planning to upgrade to 21.

**Comment by minborg** [comment]
This is how it would look like in the TPB:

```
<dependency>
  <groupId>org.jetbrains</groupId>
  <artifactId>annotations</artifactId>
  <version>21.0.1</version>
  <scope>provided</scope>
</dependency>

```

**Comment by minborg** [comment]
Related to https://github.com/OpenHFT/OpenHFT/issues/49
