### ISSUE TITLE
Documentation refers to ChronicleMapBuilder#entrySize,keySize but missing on Object

### ISSUE THREAD

**Issue by psg9999** [OpenHFT/Chronicle-Map#29]
I'm using 2.1.10 and trying to change the entrySize appropriately but apparently this was removed at some point.  Documenation still refers to this function (https://github.com/OpenHFT/Chronicle-Map#dont-forget-to-set-the-entrysize) and the exception that I receive also states this as a solution.  

java.lang.IllegalStateException: We try to figure out size of objects in serialized form, but it exceeds 16777216 bytes. We assume this is a error and throw exception at this point. If you really want larger keys/values, use ChronicleMapBuilder.keySize(int)/valueSize(int)/entrySize(int) configurations

What is the recommended way to set the entry size on current releases?

**Comment by BoundedBuffer** [comment]
can you send the code snippet that you are using when calling the ChronicleMapBuilder.

**Comment by psg9999** [comment]
TcpTransportAndNetworkConfig tcpConfig = TcpTransportAndNetworkConfig.of(8076, new InetSocketAddress("localhost", 8077)).heartBeatInterval(1L, TimeUnit.SECONDS)
                .throttlingConfig(ThrottlingConfig.throttle(1024, TimeUnit.MILLISECONDS));

        UdpTransportConfig udpConfig;
        try
        {
            udpConfig = UdpTransportConfig.of(Inet4Address.getByName("255.255.255.255"), 5486);
        } catch (UnknownHostException e)
        {
            throw new IllegalStateException(e);
        }

        ChronicleMapBuilder<CharSequence, OrderDispatch> mapBuilder = ChronicleMapBuilder.of(CharSequence.class, OrderDispatch.class).entries(20000L)
                .replication(SingleChronicleHashReplication.builder().tcpTransportAndNetwork(tcpConfig).udpTransport(udpConfig).createWithId((byte) 1));

        try
        {
            cache = mapBuilder.createPersistedTo(FileUtils.getFile(FILE_NAME));
        } catch (IOException e)
        {
            throw new IllegalStateException(e);
        }
......

cache.put(.....


The reported statement in the exception is not the actual cause, although the function on ChronicleMapBuilder still doesn't exist.  My underlying issue is that there was a member on my object that was not serializable and the put failed b/c of this.

Thanks

**Comment by BoundedBuffer** [comment]
Can you also send also the OrderDispatch class or interface.

**Comment by BoundedBuffer** [comment]
Ok - just seen you text at the bottom of your post. So I assume this is resolved. 

Btw : it's more efficient to use interfaces with get/set methods rather than objects with serializable. ( but I appreciate this is not always possible )

Rob

**Comment by psg9999** [comment]
Thanks for the tip!  I'm in the midst of working out a good object to cache for an existing domain.

I wouldn't say this is resolved unless I'm missing the exposure of the ChronicleMapBuilder.keySize(int)/valueSize(int)/entrySize(int) functions as the documentation indicates should be possible.  I'm using maven central for the .jar so http://search.maven.org/#artifactdetails%7Cnet.openhft%7Cchronicle-map%7C2.1.10%7Cjar should be the version I have locally, even though I'm not having a technical issue anymore, I do believe there is room to clean up/correct the documentation.

**Comment by BoundedBuffer** [comment]
This is the readme for chronicle map 2.1.10

https://github.com/OpenHFT/Chronicle-Map/blob/chronicle-map-2.1.10/README.md

**Comment by BoundedBuffer** [comment]
Regarding - "...to clean up/correct the documentation."

Thanks we will take a look at the documentation.

**Comment by leventov** [comment]
@psg9999 This section in documentation is written for Chronicle Map 1.x. For Chronicle Map 2 and onwards, you have `builder.averageKeySize()/constantKeySizeBySample()/averageValueSize()/constantValueSizeBySample()/actualChunkSIze()` methods. They are more specific and don't oblige your to calculate your entry size yourself.

**Comment by leventov** [comment]
Closing this issue as README documentation doesn't refer to #entrySize() now.

**Comment by nao921** [comment]
@psg9999 regarding the precise solution you had in resolving this issue you had

The reported statement in the exception is not the actual cause, although the function on ChronicleMapBuilder still doesn't exist. My underlying issue is that there was a member on my object that was not serializable and the put failed b/c of this.

did you just merely making sure that all members of your object are serialized?  what if for some optional field you don't want them to go thru that process?

**Comment by leventov** [comment]
@nao921 yes, you are right. In the latest versions I improved the error message, now it suggest that the key/value is either not serializable or too large.

**Comment by nao921** [comment]
Thanks, @leventov still on v2.1.4 unfortunately.  And i'm doing it thru implementing BytesMarshallable as advised in the doc for performance.  Would this way ignore fields that are declare as transient?

**Comment by leventov** [comment]
@nao921 Probably implementing BytesWriter/BytesReader/BytesInterop would be slightly more efficient than BytesMarshallable.

> Would this way ignore fields that are declare as transient?
I don't understand clearly, but when implementing all the mentioned custom marshalling interfaces it's entirely your responsibility to choose what fields should be serialized, and what shouldn't. It doesn't depend on transient modifier.

**Comment by nao921** [comment]
@leventov then that is strange, i'm implementing BytesMarshallable for the class to put into the chronicle map + serialized, and i'm still getting the exact exception (even the number of bytes).

> java.lang.IllegalStateException: We try to figure out size of objects in serialized form, but it exceeds 16777216 bytes

as you mentioned it's all up to me to choose which fields to serialized. then why am i getting this exception still?

**Comment by leventov** [comment]
@nao921 Also check the class has public, no-arg constructor, OR provide `chronicleMapBuilder.objectDeserializationFactory(() -> UNSAFE.allocateInstance(MyValue.class)) /* for example */`

**Comment by nao921** [comment]
ok @leventov, it was because i wiped away Serializable from the class declaration.  now it's working.

Could you point me to some references on how to do as you suggested for better performance?

> @nao921 Probably implementing BytesWriter/BytesReader/BytesInterop would be slightly more efficient than BytesMarshallable.

**Comment by leventov** [comment]
@nao921 implement `MyValueReader implements BytesReader<MyValue> {...}`, `BytesWriter` and `SizeMarshaller`. Note they could be enums; note a single class (or enum) could implement all three interfaces. Also look at `BytesInterop`. Javadocs to these interfaces are verbose and complete, they should help you.

Then configure using `builder.valueMarshallers(reader, writer)` and `builder.valueSIzeMarshaller(sizeMarshaller)`.

Look into directory `net/openhft/chronicle/hash/serialization/internal` and serveral tests in Chroncile-Map project for many example implementations, for a plenty of JDK classes.

Note you could do the same for the key type (MyKey.class)

**Comment by nao921** [comment]
@leventov i'm actually trying to put a complex type into ChronicleMap

```java
class A implements Serializable, BytesMarshallable {
  String str_;
  List<B> list_;

  @Override public void readMarshallable(Bytes in) throws IllegalStateException {
    str_ = in.readUTF();
    List<B> list = new ArrayList<B>();
    in.readList(list, B.class);
    list_ = list;
  }

  @Override public void writeMarshallable(Bytes out) {
    out.writeUTF(str_);
    out.writeList(list_);
  }
}

class B implements Serializable, BytesMarshallable {
  String str_;

  @Override public void readMarshallable(Bytes in) throws IllegalStateException {
    str_ = in.readUTF();
  }

  @Override public void writeMarshallable(Bytes out) {
    out.writeUTF(str_);
  }
}
```

I was able to serialize + deserialize correctly with the following code:
```java
final int capacity = 2 * 1024;
ByteBuffer byteBuffer = ByteBuffer.allocateDirect(capacity);
final long addr = ((DirectBuffer) byteBuffer).address();
NativeBytes nativeBytes = new NativeBytes(addr, addr + capacity);

nativeBytes.writeObject(obj_A);
nativeBytes.finish();
nativeBytes.clear();

deserialized_A = nativeBytes.readObject(A.class);
```

however when i do it thru ChronicleMap, the objects within the list of object A are not (de)serialize correctly
```java
try {
	map = ChronicleMapBuilder
			.of(String.class, A.class)
			.entries(5)
			.averageValueSize(1000)
			.createPersistedTo(testMapFile);
	
	map.put("KEY1", obj_A);
} catch (IOException e) {
	fail(e.toString());
} finally {
	((ChronicleMap<String, A>)map).close();
}

try {
	map = ChronicleMapBuilder
			.of(String.class, A.class)
			.entries(5)
			.averageValueSize(1000)
			.createPersistedTo(testMapFile);
	
	deserilized_obj_A = map.get("KEY1");
} catch (IOException e) {
	fail(e.toString());
} finally {
	((ChronicleMap<String, A>)map).close();
	testMapFile.delete();
}
```

the first way that's working i see that the objectserializer was of BytesMarshallableSerializer.

However when doing it thru chroniclemap, i see that it's using JDKObjectSerializer.  is it required that i need so specify the objectserializer i want a chroniclemap instance to use thru `.objectserializer()`?

**Comment by leventov** [comment]
@nao921 This "internal", encoded serialization mechanism is old, slow, and often puzzling. I recommend to speicfy external `BytesMarshaller` implementation (in your case `BytesReader`/`BytesWriter` are not applicable, because the marshalling size should be calculated non-trivially. `BytesReader`/`BytesWriter` are better only when the size is constant or immediately known, i. e. marshalling `int[]`).

See https://github.com/OpenHFT/Chronicle-Map/blob/0f827769423c8c9bce0e7a1cdb11aeb765910a32/src/test/java/net/openhft/chronicle/map/example/ComplexSerializationTest.java I have added; it works.

**Comment by nao921** [comment]
@leventov thanks for the pointer!  i got it working with class A and B both implementing BytesMarhsalable.  key point is to use the stop bit and the loop rather than what i did earlier with writeList and readList.
