### ISSUE TITLE
Stateless client - batch and/or async

### ISSUE THREAD

**Issue by dmk23** [OpenHFT/Chronicle-Map#30]
I am investigating Chronicle Map as a potential replacement of Redis - with concurrency in mind. In our architecture we would be looking to replace a "large" Redis instance that currently has multiple clients connecting to it causing latency pileups due to Redis' blocking nature.

The issue is that we need to make requests in random batches of ~1000. With Redis we are able to make a single request via a Lua script (or multi-get / multi-set commands) and receive a single response. In the documentation on Chronicle Maps stateless client I see that the remote calls are blocking and can be made only one key at a time, so for us the solution is not obvious.

While I am considering passing off each individual key task to a threadpool running X blocking threads at a time, I wonder if there might be a better solution that could take advantage of doing RPC in batches and perhaps work asynchronously. As I do not see this available currently, my questions are whether this is an enhancement you might consider or if you could perhaps point me to if/how we could write our own solution for doing this - which we'd be open to contributing back...

**Comment by peter-lawrey** [comment]
What is the problem you are trying to solve by using batching?  There is a
good chance this can be solved another way.
Btw chronicle engine can be used to support remote batches of any kind
including updates.
Would you consider using engine?
Eg you can easily add an operation which takes a set of keys to return as a
sub map.

Regards,
Peter.

**Comment by dmk23** [comment]
Our requirement is to process user requests that touch ~1000 random keys at the time.

To do that we want to retrieve them from the data store in the most performant manner possible. With Redis it is possible to make multi-key requests to the server - sharing the communication overhead. With Chronicle Map Stateless client it does not look possible out-of-the-box at the moment...

I have not had chance to review Chronicle Engine in depth yet. Is it just a query layer for Chronicle Map? What are the batch APIs? Does it combine the communication overhead of individual key ops? Are there any performance benchmarks to review? Any direction is appreciated...

**Comment by leventov** [comment]
dmk23, stateless client is going to be replaced with Engine in a mid-term. It is already not supported for ChronicleMap 3.x.

Engine should be able to perform some lambda in the context of Chronicle Map on the server. It send the lambda over network in a serialized form. It could be some Function implementation with apply() and 1000 fields. Or, in Java 8, the runtime is even able to capture variables used in lambda body and make it Serializable automatically.

**Comment by dmk23** [comment]
Thanks for clarification - I did not see any deprecation notices in the Stateless Client section on the Chronicle Map docs. Are there any good examples for converting Stateless Client code to Engine?

Also, when is 3.x expected to become stable, at least as far as file formats concerned? I like some other 3.x features (e.g. garbage-less iterators), but wonder when it would be safe to use...

**Comment by peter-lawrey** [comment]
This assumes your clients are on different machines.  If you are on the
same machine, you wouldn't use remote access.  Chronicle Engine supports
accessing data directly from multiple JVMs without using TCP.  This is much
faster. i.e. a get can take around 1 micro-second.

For remote machines...
It is a bit early to say, but individual get() should be possible in around
20-50 micro-seconds. This mean that 1000 gets could take as little as 50
ms.  However we also have a batch API under development. You can do the
following.

MapView<String, ?, String> map = acquireMap("my-map", String.class,
String.class);

Set<String> set = ...
Map<String, String> subset = map.applyTo(m -> {

    Map<String, String> ret = new HashMap<String, String>();
    for (String key : set) {
        ret.put(key, m.get(key));
    }
    return ret;
});

At the moment this will actually do 1000 gets remotely, but the change
under development is to do this on the server. Once this change has been
released you will be able to perform arbitrary lambda functions on the
server to either query or update the server.  As serializing a lambda is a
bit expensive (doesn't matter in this case, but for short operations it
will) You can create an enum for each function you wish to perform.  This
will reduce the serialization/deserialization cost of the function
dramatically.

Regards,
   Peter.

**Comment by dmk23** [comment]
Yes, at the moment our requirement is to do this on different machines. Our application services are spread out across a cluster of nodes that need to look up key-values from a central store.

I'll experiment with your sample code. One thing that is not clear is how to establish a TCP connection using the Engine. Doesn't acquireMap refer to a file on the local filesystem?

Next, is there a reason these 1000 gets have be done serially in one thread? Why not submit 1000 get() tasks to a pool of say 20 threads, shouldn't this improve throughput / reduce latency?

Also seems to me your code is for Java 8, which we won't be able to move to for some time until some other 3rd party software we rely on is certified to work. I am sure that's the case for many others...

**Comment by leventov** [comment]
> Next, is there a reason these 1000 gets have be done serially in one thread? Why not submit 1000 get() tasks to a pool of say 20 threads, shouldn't this improve throughput / reduce latency?

For get()s, sure parallelizing will reduce costs. For put()s, if you have concurrency requirements, i. e. multi-key lock before updating all of them, of cause it should be in one thread.

---
Chronicle Map 3.x requires Java 8.

**Comment by BoundedBuffer** [comment]
The stateless client gives better performance if you use a number of threads - see https://github.com/OpenHFT/Chronicle-Map#how-to-speed-up-the-chronicle-map-stateless-client <https://github.com/OpenHFT/Chronicle-Map#how-to-speed-up-the-chronicle-map-stateless-client>

I don’t see that you would gain a performance benefit, in using batches, unless you are compressing the batch of data. All the data will have to be sent via tcp anyway, even if its in a batch.

**Comment by dmk23** [comment]
@leventov : Now that we know Java 8 is required for 3.x we are going to take another, much closer look at speeding up our migration.

@BoundedBuffer : The main benefit is replacing 1000 TCP trips with a single one which should make a big difference in latency. Compression and possibly prioritizing server execution within the batch (e.g. grouping tasks by the lockable segments of a concurrent map) are just additional benefits.

Either native batch APIs or a "standard" way to simplify parallel / async execution via a threadpool seem like natural additions to the Engine...

**Comment by BoundedBuffer** [comment]
> On 7 Jul 2015, at 11:15, dmk23 <notifications@github.com> wrote:
> 
> @BoundedBuffer <https://github.com/BoundedBuffer> : The main benefit is replacing 1000 TCP trips with a single one which should make a big difference in latency. Compression and possibly prioritizing server execution within the batch (e.g. grouping tasks by the lockable segments of a concurrent map) are just additional benefits.


I agree about compression and prioritisation, however, under high load the chronicle map stateless client consolidates many small TCP request into a single request ( when run with a number of threads. )

**Comment by BoundedBuffer** [comment]
FYI : you may find these methods useful. ( they work with Java 7 and the stateless client )


/**
 * Apply a mapping to the value returned by a key and return a result. A read lock is assumed.
 *
 * @param key      to apply the mapping to
 * @param function to calculate a result
 * @param <R>      return type.
 * @return the result of the function, or null if there is no entry for the key.
 */
<R> R getMapped(K key, @NotNull Function<? super V, R> function);

/**
 * Apply a unaryOperator to the value for a key and return a result. A write lock is assumed.
 * <p> If there is no entry for this key null will be returned
 *
 * @param key           to apply the mapping to
 * @param unaryOperator to alter the value and calculate a result
 * @return the result of the function.
 */
V putMapped(K key, @NotNull UnaryOperator<V> unaryOperator);

**Comment by dmk23** [comment]
Good to know re: TCP request consolidation, I did not see that clearly stated in the doc.

One more thing that might be very useful is having some benchmarks / best practices on how many threads to use for this kind of batching. There has to be some sweet spot between serial execution and too many threads competing for JVM and hardware resources.

Now, regarding getMapped / putMapped, correct me if I am wrong but they still only apply to a single key vs. a batch? Are there any other benefits beside pushing execution of the function into the server?

**Comment by leventov** [comment]
Some numbers to keep in mind:
- single key operation on a Chronicle Map (without writing KB, MB-large value, e. g. just Long value): 0.2 - 1 microsecond
- Amount of work is not recommended to parallelize / split down in Java 8 streams: when < 100 microseconds
- Number of parallel writing threads Chronicle Map can scale almost linearly: number of chunks / 4. Number of chunks could be configured to any number, not recommended a chunk to be < 128 entries average full. I. e. if your Map is going to have 1000 entries, it is not recommended to configure more than 8 chunks. Also, makes some sense to stick to power-of-two number of chunks.

**Comment by leventov** [comment]
> Now, regarding getMapped / putMapped, correct me if I am wrong but they still only apply to a single key vs. a batch? Are there any other benefits beside pushing execution of the function into the server?
A single key. Remote multi-key query (i. e. just an arbitrary function applied to the map on the server side) is not possible right now. This possibility should appear in Engine soon

**Comment by BoundedBuffer** [comment]
Strictly speaking you are correct, however the function is free to do anything it wants including writing and reading to a number of keys ( I think )

**Comment by dmk23** [comment]
Good point re: "the function is free to do anything it wants" though to operate on other keys in a batch it  would have to get them from somewhere. In its current signature I do not see how it could be done

**Comment by BoundedBuffer** [comment]
Regarding my comment "however the function is free to do anything", Roman pointed out to me - "this is not possible due to key segment locking."

**Comment by peter-lawrey** [comment]
While the server supports a batch of data, this doesn't imply a
transaction.  If you collect data for multiple keys, this data may be
changed on the server while you are collecting this data.

Currently the server handling software is single threaded.  This means that
if you only access the data from remote clients, it isn't possible to have
a change in the middle of accessing this data.  This is not guaranteed
behaviour, but how it happens to work currently.

It would be useful to chat more directly.  You can email me on
peter.lawrey@chronicle.software.

Regards,
   Peter.

**Comment by dmk23** [comment]
Thanks to everyone for your comments. I think as the next step for this particular issue I am going to need to do some prototyping / testing - which has just started. I've discovered Chronicle Map just this week, still learning basics but it already looks like this will be our solution to several problems.

I can reach out via email if that's preferred way to talk, though realistically most questions tend to arise when we try something out and run into one issue or another...

Also, we've completed the review of dependencies and will be migrating everything to JDK8 ASAP.

**Comment by dmk23** [comment]
I wanted to report my test results for the test of Chronicle Map as a Redis replacement, with the code for this use case available in the related issue https://github.com/OpenHFT/Chronicle-Map/issues/33

The sweet spot in terms of # of threads in our case seems to be 32. Higher max threads (>64) or lower (16) cause ~10% slowdown vs. optimum. Trying to get rid of the executor and run all requests serially in one thread caused ~80% slowdown vs. the optimum case.

Unfortunately even the optimum case in our test loses out to Redis by far. Batches of 1000 records  took ~40ms to process with Chronicle Map, but was only ~9ms in our historic tests with Redis. The numbers are averaged for ~2000 batches with extensive warmup.

So for now we are going back to Redis and it seems like there should be a clear performance benefit for implementing native support for batch processing into Chronicle Map

**Comment by leventov** [comment]
@dmk23 Am I understand right, that the ChronicleMap instance and your client code are run on different servers?

**Comment by dmk23** [comment]
Correct. Same servers and same datasets that we've run Redis on. We might revisit Chronicle Map when we are able reconsider the overall deployment architecture and run local / embedded instances for this component, but that's not going to happen until we are really pressed to

**Comment by leventov** [comment]
@dmk23 Hm, in this case I don't understand, how you could ever win from parallelizing accesses to statelessClient, which  1) `synchronized` on a single resource inside 2) goes through a single socket network connection.

ChronicleMap is superior to Redis in terms of server-side parallelism. On "client", (called statelessClient  in Chronicle Map historically), it is single-threaded (`synchonised` for safety, but single-threaded in principle).

Even if you have many client *servers*, you could hardly benefit from Chronicle Map's server-side parallelism, because it multiplexes it's network deals through a single thread and selector.

So the "Chronicle Map way" is "move your map to the client's memory", i. e. many Maps, replicated to each other, sitting in memory of each "client". You could update the Map only from a single node ("master"), but not restricted to.

I explained above why Chronicle Map shouldn't be expected to be faster than Redis with your architecture. Why it is slower? I'm 99% sure, because Stateless Client is not suited from batch operations. Instead of performing 1 network communication session, it performs 1000 of them.

It's indeed a miss (through you should understand, that "statelessClient" use of Chronicle Map was not intended use case from the start, just filling the gap for exceptional situations. This post is whole about that.)

We should consider this in Engine, which will replace StatelessClients

**Comment by dmk23** [comment]
I undertook this test because of the comments in this thread re: consolidation of TCP communication and because of the docs that were also suggesting multi-threading access to Stateless Client to increase performance (which indeed turned out to be the case).

Yes, I understand the "Chronicle Map way" is to keep all data local. But in our case we are not ready to completely redo architecture for existing applications, though may consider this in the future. However, if you are offering / supporting any kind of remote access (Stateless Client or Engine) It should be helpful to clearly explain all the performance caveats and/or perhaps offer proper batch/parallel/async clients. The reason I opened this issue is exactly because I did not see that clearly laid out.

Look forward to seeing your approach in the Engine as the project gets developed. Hopefully you would provide some docs / examples on implementing the cases of batch access.

**Comment by peter-lawrey** [comment]
It would be helpful to us if you provided the source to your tests so we
could see the issue for ourselves.
This way we could tell you if we have optimised for this use case in the
future.
The reason we haven't optimised for remote access is that it is so much
slower (around 30x slower ) than having a local copy that we assume any one
doing this isn't concerned about performance. Ie redis on localhost is 30x
slower than Chronicle Map accessed in process.
However, as you say there are use cases where performance requirements have
increased but there isn't an opportunity to re-architect the solution.
It is this situation were we know we need to improve in the future.

Regards, Peter.

**Comment by dmk23** [comment]
We cannot provide the actual code since it is part of our proprietary system. However I'd be happy to provide a few pointers on making Chronicle a viable alternative to Redis:

#### 1. Commands ####

Here is what Redis currently can do: http://redis.io/commands . I suggest looking at the commands by group, especially functionality available for each data structure type. Most of that is already possible in Chronicle Map but it might be helpful to provide something like customized / optimized serializers. But consider that many Redis applications (though not our simple KV cache example) already heavily rely on using Hashes, Sets, Lists and Sorted Sets as defined by Redis - so you should look into how people use them and consider offering something similar natively.

#### 2. Scripts ####

We do most of our Redis heavy lifting using Lua scripts that can take an arbitrary number of keys and arguments: http://redis.io/commands#scripting , all submitted via one single command. We use that instead of something like MULTIGET because Redis has huge RAM overhead for storing top-level keys and we are packing / unpacking them via Lua scripts that implement the strategy described in the link below. Even Redis aside you might want to consider its use for Chronicle Map.
http://instagram-engineering.tumblr.com/post/12202313862/storing-hundreds-of-millions-of-simple-key-value

#### 3. Java Clients ####

Since Chronicle Map is for Java developers, look at the Java clients for Redis (especially starred ones): http://redis.io/clients#java . We are using Jedis, but other projects could also give you some ideas. Note that while in our design we do almost everything via atomically applied Lua scripts (think of them as an arbitrary multi-key / multi-arg lambda thats can be efficiently cached by server), many people rely on command pipelining:  http://redis.io/topics/pipelining . In any case, there should be a way to execute a batch of commands together and a single way to do that should be enough.

#### 4. Benchmarks ####

You should take a look at Redis' own published use cases and benchmarks. There are plenty of tests you can adopt to Chronicle Map : http://redis.io/topics/benchmarks . Note that for localhost benchmarks you should compare apples-to-apples, which means using Redis UNIX domain socket instead of TCP/IP.

If you do decide to address the case for optimizing remote access and matching Redis functionality I think Chronicle Map could become a no-brainer migration alternative, due to stronger persistence / replication / Java integration. Redis in the past has toyed with memory-mapped files, but then all that functionality was removed which means at certain point it is becomes all about buying RAM, with no possibility to fall back on SSD or even spinner disks if only part of a dataset is expected to be hot.

Hopefully some of these suggestions may be helpful.

**Comment by peter-lawrey** [comment]
Hello dmk23,
   Most of this possible with Engine.  Would you consider using this
instead as this our general direction for all remote access.
   What is lacking is documentation to show this and we will add these over
time.

   For example, you can call an arbitrary lambda or predefined function on
the server from the client. For a batch get you can do

   List<Key> keys = ...
   List<Value> values = map.applyTo(m -> {
       List<Value> values = new ArrayList<>();
       for(Key k : keys)
            values.add(map.get(k));
       return values;
   });

Instead of using a lambda you can define an `enum` of predefined functions
e.g.

https://github.com/OpenHFT/Chronicle-Engine/blob/master/src/main/java/net/openhft/chronicle/engine/map/remote/MapFunction.java

We also have a function for querying and/or updating either an individual
entry, or the map as whole remote.

Note: update is asynchronous by default so it acts like a pipelined
request. Some more are defined here

https://github.com/OpenHFT/Chronicle-Engine/blob/master/src/main/java/net/openhft/chronicle/engine/map/remote/MapUpdate.java

You can send a number of asynchronous calls and wait for a synchronous one.
A simple example is put which is asynchronous by default.

    map.put(key1, value1); // async
    map.put(key2, value2); // async
    map.put(key3, value3); // async
    map.size(); // sync

As size() is synchronous it must wait for the asynchronous calls to
complete before returning it's result.

   I think using benchmarks only over loop back is valid if you have a
business requirement to use loop back.  If your requirement is for two
processes to talk together, it is valid to compare the fastest method
available.

Regards,
   Peter.

**Comment by danielshaya** [comment]
Hello dmk23,

I'm looking into creating documentation for Chronicle-Engine. In particular
I want to be able to explain some Redis features in terms in Chronicle
(thanks for all the pointers to Redis docs you provided). I'm sure this
sort of documentation would have been useful for you.

In terms of your actual test, I created a test using Chronicle-Engine to
touch 1000 records out of a total map of 10,000.  Even without a well tuned
system, and on my laptop I was able to run this test in less than 0.5ms.

Please contact me at daniel.shaya@chronicle.software as I'd like your input
into how to take this further.

Regards
Daniel

**Comment by dmk23** [comment]
Sorry for the delay - my recent attention has been elsewhere.

I'd like to take a fresh look at the Engine once it is stable / released, documented and benchmarked - ideally including the use cases I have described here - especially access over the network. We are also going to have to complete our migration to Java8 first, which is now a priority.

It would be helpful if you could explain/document the semantics / functionality of what kind of lambdas are possible. In your example I see a lambda operating on N keys of the same type and returning N values of the same type. What if I want to return a scalar or multiple scalars / keys or some other custom type I want to define? What if I want to have a lambda [atomically] operate on multiple maps stored within the same server? Is this possible (in Redis Lua it is)? How to implement this? How would it perform? Those are the kind of things I'd like to see fully documented and benchmarked.

In many of our use cases a lambda (as a counterpart of a Redis Lua script) would need to operate on multiple entities of different types. It is my impression that managing multiple maps and operating on them atomically / transactionally may be a problem. Just having to maintain multiple files to serialize them (and manage size limits for each) is an inconvenience. Why not consolidate multiple maps into single DB files and manage their expansion / compaction as needed?

Now to Daniel's questions here are my comments / suggestions : 

1. Are you touching 1000 records in a single lambda vs. separately (serially or parallel)?
2. On your laptop, is the map running in the same process you are benchmarking? Even the local socket connection would be way faster than if you access the map on a different box - you should document both cases and benchmark them vs. a Redis Lua script
3. I would suggest running lookups using a bigger map. Try touching 1000 records within 10M or maybe 100M total database. I'd expect larger maps would not have the benefit of greater data locality and the benchmark would be a lot more realistic.
4. Try the same benchmark with a larger map and a cold restart of a JVM. In a real-world scenario absent a quick way to tell JVM to preload the mmap'd file this would generate lots of random (very slow!) disk reads. Redis would load everything into RAM upon restart - there ought to be a similar feature in the Chronicle Map to make it production-friendly.
5. Not directly related to this benchmark per se, but a significant limitation of Chronicle Map is lack of support for ordered data structures that can be scanned as a NavigableMap. In most Key-Value DB-like use cases data ordering / scans are very important. In Redis while there is no ordering in the top-level key space, it is possible to create large Lists/Sets/Sorted Sets with millions of entries.

At the moment we are limiting our use of Chronicle Map to storing a few supporting entities off the "hot path", but would like to revisit the broader use of Map/Engine as some of the issues raised here get addressed / documented / benchmarked... You seem to have built the project on a very solid foundation / primitives, but some functionality remains to be developed / documented / proven...

**Comment by peter-lawrey** [comment]
Rob, Can you see if these questions can be added to the FAQ?

**Comment by RobAustin** [comment]
@dmk how are you getting on with chronicle-map / chronicle-engine, do you still require any additional functionality, perhaps around those points you mentioned above. Have you considered us working for you on a more commercial basis ?

**Comment by dmk23** [comment]
We have the projects that may have required chronicle components on indefinite hold
