### ISSUE TITLE
Download Install is not working

### ISSUE THREAD

**Issue by ghost** [OpenHFT/Chronicle-Map#312]
Simple download of Chronicle-Map repository.  Unzip files, import into Eclipse.  In net.openhft.chronicle.hash.impl will not compile due to import net.openhft.chronicle.core.shutdown.PriorityHook; not being found.  Second error: Within package net.openhft.chronicle.map; there is no reference for CompiledMapIterationContext on line 296.

**Comment by ghost** [comment]
Is there any resolution of this?  Short of decompiling JAR's how do I get access to the missing java classes?

**Comment by RobAustin** [comment]
CompiledMapIterationContext is created via the annotations processor, run 

```
$mvn install -U
```
from the shell and it should create this class for you.

**Comment by minborg** [comment]
Sometimes you have to tell the IDE that the generated-sources/annotations directory should count as source code. For IntelliJ, you do like this. I think there is a corresponding way for your IDE.

![image](https://user-images.githubusercontent.com/7457876/128471177-aa71c207-78f2-4be9-a74d-716a14c9a050.png)
