### ISSUE TITLE
HugeSparseMapTest takes 20 minutes on CI boxes

### ISSUE THREAD

**Issue by nicktindall** [OpenHFT/Chronicle-Map#317]

**Comment by minborg** [comment]
Is it still slow? I know Peter did some work on sparse files but maybe not related to Map? How do we progress with this issue @nicktindall ?

**Comment by nicktindall** [comment]
I re-enabled it, and it looks fixed. It:
- Runs fine on my machine
- But it [failed](https://github.com/OpenHFT/Chronicle-Map/runs/4698583819?check_suite_focus=true) in github actions, 
- Succeeded quickly [in TC](https://teamcity.chronicle.software/buildConfiguration/Chronicle_ChronicleMap_SnapshotLinux64/641135?showRootCauses=false&expandBuildChangesSection=true)

**Comment by nicktindall** [comment]
Please merge that PR if you're happy, merging it will close this issue
