### ISSUE TITLE
Respect BytesMarshallable#usesSelfDescribingMessage

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Map#318]
And use Wire Marshaling as appropriate

**Comment by JerryShea** [comment]
Note that we can tell the map builder to use Wire marshalling with
```
.valueMarshaller(new MarshallableReaderWriter(Bar2.class))
```

**Comment by minborg** [comment]
What is the status of this issue @JerryShea ? What needs to be done (if anything)?

**Comment by JerryShea** [comment]
@minborg Chronicle Wire method readers and writers ask the DTO (`BytesMarshallable#usesSelfDescribingMessage`) whether to use Wire marshalling vs Bytes marshalling but Chronicle Map uses an alternate mechanism to decide how to marshall a DTO.

IMO all I think we should do is document that Map does not refer to `usesSelfDescribingMessage`. @foroughgoudarzi @rogersimmons what do you think?

**Comment by rogersimmons** [comment]
Agreed. @foroughgoudarzi - could you add a sentence or two to this effect. Thanks

**Comment by JerryShea** [comment]
Now supported with `CommonMarshallableReaderWriter` - see #481
