### ISSUE TITLE
concurrent duplicate keys break stateless client

### ISSUE THREAD

**Issue by dmk23** [OpenHFT/Chronicle-Map#33]
We are trying to implement the "multi-threaded batch" design as discussed in https://github.com/OpenHFT/Chronicle-Map/issues/30 . We created an executor service and are submitting Callable items with a code that looks like that:

```
Collection<Item> items = ... ; // our tasks pre-initialized
ExecutorService runner = new ThreadPoolExecutor(16, 256, 300L, TimeUnit.SECONDS, new LinkedBlockingDeque());
List<Future<Item>> futures = runner.invokeAll(items)
for (Future<Item> future : futures) {
    Item item = future.get();
    ... application logic ...
}

class Item implements Callable<Item> {
  public byte[] key = ... ; // initialized in advance
  public Item call() {
    byte[] value = stateless_client.get(key); // blocks the thread
     ... application logic ...
    return this;
  }
}
```

In some of our test examples we had several ```Item``` objects with the same key. All these examples failed, being blocked in the for loop on ```future.get()``` call. Once we've instrumented the ```call()``` code with logging before and after stateless client access we've discovered that for duplicate keys multiple tasks get submitted, but the first one to complete prevents all others from exiting, so they block forever - blocking the whole batch. When there are no duplicates the code works fine.

This seems like a significant defect to me as it may not always be possible to assure that tasks with the same key would not be submitted to the stateless client. It would be better if Chronicle Map be able to handle this case properly. I've tested this with v2.2.0

**Comment by leventov** [comment]
This is strange. I don't see how Statless/ChronicleMap communication accouts equivalent keys. This test: https://github.com/OpenHFT/Chronicle-Map/blob/af48ed63c57eb47ef093d343a2bf402b78b153d6/src/test/java/net/openhft/chronicle/map/StatelessClientDuplicateKeyTest.java passes.

**Comment by dmk23** [comment]
Are you asserting that your test case successfully exits and does not block? The assertions in this case are not supposed to fail, just the duplicate keys are going to block forever on ```.get()```

You should also consider testing a broader mix of keys and ```byte[]``` key type

**Comment by leventov** [comment]
@dmk23 yes, exits. Ok I'll test different byte[] keys tomorrow

**Comment by leventov** [comment]
No problems with byte[] keys. I don't understand *how* duplicate keys could be an issue, because internally Remote call implementation code doesn't check key contents, for "coalescing requests" or something like this, i. e. There is just no difference - duplicate or unequal keys.

**Comment by dmk23** [comment]
I just re-ran my original test and now it magically worked. Not sure what changed to make it possible, but I am having trouble isolating the original problem now. It could be one of those Heisenbugs. I do remember that when the issue was first seen it was failing as originally documented. The problem might also be somewhere with the map server and how it manages state, but I cannot think of anything else... The test worked for me again after the map server restart...

Probably the issue can be closed for now, especially that you'll be sunsetting the Stateless Client soon
