### ISSUE TITLE
Improve module system friendliness 

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Map#333]
Add a default module name and indicate modules to  open/export in MANIFEST

**Comment by hft-team-city** [comment]
Released in [Chronicle-Map-3.22ea3](https://github.com/OpenHFT/Chronicle-Map/releases/chronicle-map-3.22ea3), [BOM-2.22ea23](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea23)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Map-3.22ea3](https://github.com/OpenHFT/Chronicle-Map/releases/chronicle-map-3.22ea3), [BOM-2.22ea29](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea29)
