### ISSUE TITLE
ExitHookTest fails under Java 17

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Map#337]

**Comment by minborg** [comment]
This is due to the fact that the spawned child processes do not inherit the parent's JVM parameters.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Map-3.22ea4](https://github.com/OpenHFT/Chronicle-Map/releases/chronicle-map-3.22ea4), [BOM-2.22ea29](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea29)
