### ISSUE TITLE
ChronicleMapTest.testAcquireUsingLockedWithString fails under Java 17

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Map#338]

**Comment by minborg** [comment]
Apparently, Java 17 does a better job internalizing/de-duplicating strings so, we have to explicitly create a new empty string

**Comment by hft-team-city** [comment]
Released in [Chronicle-Map-3.22ea4](https://github.com/OpenHFT/Chronicle-Map/releases/chronicle-map-3.22ea4), [BOM-2.22ea29](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea29)
