### ISSUE TITLE
The file the map is serialized from has unexpected length 0

### ISSUE THREAD

**Issue by alamar** [OpenHFT/Chronicle-Map#342]
Very often, in tests or debugging sessions, the annoying error message from the subject is produced.

When map creation is preempted, it often leads to map file having zero length. Chronicle Map will not overwrite such maps, despite there being nothing to lose due to zero length.

Maybe we should issue a warning in this case and then overwrite the zero-length file?

**Comment by glukos** [comment]
FYI
This can be reproduced locally if ConcurrentReceiversTest is running until failure.
I masked it for Build-All by using distinct map dirs for different tests.

**Comment by minborg** [comment]
What is the status of this @alamar ? Shall we merge the PR or not?

**Comment by alamar** [comment]
I have not seen this error for some time, and @glukos told me there's a non-empty check earlier in the code, so it should only arise when debugging, pausing/killing JVM. Let's close it now, we can re-open later if we see this happening again.

**Comment by alamar** [comment]
I can reliably see this issue when creating map from two processes: https://github.com/OpenHFT/Chronicle-Map/pull/437

**Comment by hft-team-city** [comment]
Released in [Chronicle-Map-3.23ea3](https://github.com/OpenHFT/Chronicle-Map/releases/chronicle-map-3.23ea3), [BOM-2.23ea96](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea96)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Map-3.22.8](https://github.com/OpenHFT/Chronicle-Map/releases/chronicle-map-3.22.8), [BOM-2.22.149](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22.149)
