### ISSUE TITLE
chronicle-map "put" operation may result in Dead Lock

### ISSUE THREAD

**Issue by snecker** [OpenHFT/Chronicle-Map#36]
when i create a map  persisted to local file like :

```
ChronicleMapBuilder<String, ?> builder = ChronicleMapBuilder.of(String.class, Object.class);
builder.createPersistedTo(new File("myfileUri"));
 ChronicleMap<String, ?> map= builder.createPersistedTo(file);
```

then use it concurrent environment. its data was initinalized in one thread and then in other thread,

when i called
```
map.put("201401100900194",30381)
```
that would result in DeadLock exception like:
```
java.lang.RuntimeException: Dead lock
	at net.openhft.chronicle.hash.impl.BigSegmentHeader.updateLock(BigSegmentHeader.java:289)
	at net.openhft.chronicle.map.impl.CompiledMapQueryContext$UpdateLock.lock(CompiledMapQueryContext.java:850)
	at net.openhft.chronicle.map.MapMethods.put(MapMethods.java:77)
	at net.openhft.chronicle.map.VanillaChronicleMap.put(VanillaChronicleMap.java:465)
	at com.laimi.sync.client.fj.chroniclemap.TestChroniclemap.testDeadLock(TestChroniclemap.java:91)
```
i retry it in unit test and refer the same file,it still throw the same exception.

but when i put other key like 
```
"map.put("201401100900195",30382)"、
"map.put("201401100900196",30383)"
```
it will be ok

how to solve it,am i missing something?

**Comment by RobAustin** [comment]
>i retry it in unit test and refer the same file, it still throw the same exception.

could you send us the unit test that fails, preferably by issuing a pull request ( so that we can add it to the chronicle map project ).

Rob

**Comment by leventov** [comment]
https://higherfrequencytrading.atlassian.net/browse/HCOLL-378

**Comment by leventov** [comment]
The recent `3.4.0-beta` release contain new `ChronicleMapBuilder.recoverPersistedTo()` method that should solve this issue.
