### ISSUE TITLE
Is creating multiple ChronicleMap instance within JVM not performant?

### ISSUE THREAD

**Issue by the123saurav** [OpenHFT/Chronicle-Map#364]
We are planning to use ChronicleMap on a single JVM process.
Our use-case involves typical: Read -> Modify -> Update cycles on a key.
There could be multiple requests concurrently for different keys and we want to improve performance for such cases.
Is there a way I can know the segment a particular key would map to so that I can just take a lock on that.
Basically, our idea is to create N read-write locks where N equals to number of segments in CM.
Then we use 1 of the read-write lock for the Read -> Modify -> Update cycle.

**Comment by minborg** [comment]
Increasing the number of segments would reduce the probability of lock contention but would increase the total required data size (ChonicleMapBuilder::minSegments).

**Comment by minborg** [comment]
Also, you can create several CM instances as the title implies. I am closing this issue now. Please reopen if you need more info.
