### ISSUE TITLE
Document support ticket 516- Implementing Custom Serializers for ReplicatedMap

### ISSUE THREAD

**Issue by foroughgoudarzi** [OpenHFT/Chronicle-Map#368]
@foroughgoudarzi please add a description

**Comment by foroughgoudarzi** [comment]
@alamar could you please provide some info about this ticket, what should be documented?

**Comment by alamar** [comment]
I think we should discuss it with @glukos 
ChronicleMapBuilder.valueMarshaller is the setting that we want to expose in `ReplicatedMapCfg`

**Comment by foroughgoudarzi** [comment]
@glukos could you please provide more info on this?

**Comment by foroughgoudarzi** [comment]
Stock ReplicatedMapCfg is not able to express valueMarshaller(), but it is possible to do in the subclass:
 
public class MarshallableReplicatedMapCfg<K, V extends Marshallable> extends ReplicatedMapCfg<K, V> {

    public ChronicleMapBuilder<K, V> mapBuilder(byte localHostId) {
        ChronicleMapBuilder<K, V> builder = super.mapBuilder(localHostId);
        builder.valueMarshaller(new MarshallableReaderWriter<V>(valueClass()));
        return builder;
    }
}
Then it should be added as an alias:
ClassAliasPool.CLASS_ALIASES.addAlias(MarshallableReplicatedMapCfg.class);

and finally, specified in the yaml file explicitly:

  [hawkorders.map](http://hawkorders.map/): !MarshallableReplicatedMapCfg {


After these changes, the reproducer passes without exceptions.
