### ISSUE TITLE
Chronicle-Map Replication Close Issue

### ISSUE THREAD

**Issue by maxime-leur** [OpenHFT/Chronicle-Map#37]
Hi,

I have issue when I use "close()" function on many empty ChronicleMap in the same ReplicationHub.
The "close()" function send an NullPointerException:
```
Exception in thread "main" java.lang.NullPointerException
	at net.openhft.chronicle.map.VanillaChronicleMap.longSize(VanillaChronicleMap.java:1041)
	at net.openhft.chronicle.map.VanillaChronicleMap.size(VanillaChronicleMap.java:1050)
	at java.util.AbstractMap.equals(AbstractMap.java:447)
	at java.util.ArrayList.remove(ArrayList.java:510)
	at net.openhft.chronicle.map.ChannelProvider$ChronicleChannel.close(ChannelProvider.java:639)
	at net.openhft.chronicle.map.ReplicatedChronicleMap.close(ReplicatedChronicleMap.java:346)
```

After analyze, it seems that this error is due to the "Equals" method on "VanillaChronicleMap" (coded in java.util.AbstractMap) that return true if two VanillaChronicleMap are empty regardless if they have differents backing files.
This "Equals" issue make the ChannelProvider$ChronicleChannel.chronicleChannelList not coherent as the "remove(Object)" function does not remove correct VanillaChronicleMap.

Here is the code that failed (noticed that maps close order is different than map creation order):
```
int port = 1000;
		String remoteHost = "localhost";
		int remotePort = 2000;
		
		TcpTransportAndNetworkConfig  tcpReplicationConfig = TcpTransportAndNetworkConfig 
				.of(port, new InetSocketAddress(remoteHost, remotePort))
				.heartBeatInterval(1, TimeUnit.SECONDS)
				.autoReconnectedUponDroppedConnection(true);
		
		ReplicationHub replicationHub = ReplicationHub.builder()
                .tcpTransportAndNetwork(tcpReplicationConfig)
                .maxNumberOfChannels(1024)
                .createWithId((byte)1);		
		
		File file1 = new File("./store/file1");
		ChronicleMap<String, String> map1 = ChronicleMapBuilder.of(String.class, String.class)
				.instance()
				.replicatedViaChannel(replicationHub.createChannel(2))
				.persistedTo(file1)
				.create();
		
		File file2 = new File("./store/file2");
		ChronicleMap<String, String> map2 = ChronicleMapBuilder.of(String.class, String.class)
				.instance()
				.replicatedViaChannel(replicationHub.createChannel(3))
				.persistedTo(file2)
				.create();		
		
		map2.close();
		map1.close();	
```

Regards,

Maxime

**Comment by peter-lawrey** [comment]
Equality for Map is defined as a comparison of their contents. As such all
empty maps are equal.
This is a bug and the element should be removed by position not by
equality. Another solution would be to clear the list when finished.

Peter.

**Comment by maxime-leur** [comment]
Shoud I open a JIRA on Chronicle-Map ? or someone will do it ?

**Comment by peter-lawrey** [comment]
Only clients can open JIRAs. I will get some one to look into it.

Peter.

**Comment by RobAustin** [comment]
Jira Raised https://higherfrequencytrading.atlassian.net/browse/HCOLL-384

**Comment by leventov** [comment]
This should be fixed in the next Chronicle Map 2.x release.
