### ISSUE TITLE
Only run HugeSparseMapTest on TC

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Map#374]
GH Actions cannot run these tests.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Map-3.22ea6](https://github.com/OpenHFT/Chronicle-Map/releases/chronicle-map-3.22ea6), [BOM-2.22ea86](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea86)
