### ISSUE TITLE
wrong checksum of jar in maven repository

### ISSUE THREAD

**Issue by xfeep** [OpenHFT/Chronicle-Map#38]
when use `mvn compile` :

```shell
[WARNING] Checksum validation failed
expected a55111b4fbbd40553d263f664978c6ea9f9b96ed but is 995544ef2c57264c49e5fbd03307ebeebc5a47da 
for https://repo1.maven.org/maven2/net/openhft/third-party-bom/3.4.20/third-party-bom-3.4.20.pom
```

when use `lein deps` :

```shell
Retrieving net/openhft/third-party-bom/3.4.20/third-party-bom-3.4.20.pom from central
Could not transfer artifact net.openhft:third-party-bom:pom:3.4.20 from/to central
(http://repo.maven.apache.org/maven2/): Checksum validation failed, expected 
a55111b4fbbd40553d263f664978c6ea9f9b96ed 
but is 995544ef2c57264c49e5fbd03307ebeebc5a47da

```

**UPDATE**:  chronicle-map version
```
[net.openhft/chronicle-map "2.3.3"]
```

**Comment by xfeep** [comment]
This issue make it be **quite difficult** when used in typical clojure projects where   [leiningen](http://leiningen.org/) is heavily used in dev environments.
leiningen will refuse to download the jar which has  wrong checksum.

**Comment by RobAustin** [comment]
I've seen this issue come up a few times, however sonatype nexus won't let us upload anything without signing it ( and then this is check by  sonatype nexus ) - so I have no idea what this issue could be.

**Comment by xfeep** [comment]
@RobAustin  I don't know whether this stackoverflow link [How do I fix incorrect checksums in my Nexus repository](http://stackoverflow.com/questions/5751572/how-do-i-fix-incorrect-checksums-in-my-nexus-repository) is helpful or not.
