### ISSUE TITLE
Guard closing

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Map#382]
Closing may fail if there are outstanding write locks. We could try and wait for a while closing for all the locks to be released.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Map-3.22ea6](https://github.com/OpenHFT/Chronicle-Map/releases/chronicle-map-3.22ea6), [BOM-2.22ea86](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea86)
