### ISSUE TITLE
Test/documentation of Chronicle Map on docker

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Map#387]
In the [documentation](https://github.com/OpenHFT/Chronicle-Map/blob/2881940e49fb1c74cdd6692b1235bb4dca8ea2c7/docs/CM_FAQs.adoc#will-chronicle-map-work-in-docker-environments) we say that we have not tested CM with docker.

I would hope that so long as we follow the [same advice we give CQ users](https://github.com/OpenHFT/Chronicle-Queue/blob/3498a1b582dd3adf6d26491e47eb9ac90cb6c665/docs/FAQ.adoc#does-chronicle-queue-work-in-linux-containers), it should work absolutely fine.

Can we verify and update the doco?

**Comment by hft-team-city** [comment]
Released in [Chronicle-Map-3.23ea0](https://github.com/OpenHFT/Chronicle-Map/releases/chronicle-map-3.23ea0), [BOM-2.22.129](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22.129)
