### ISSUE TITLE
Using ChronicleMap as a Cache?

### ISSUE THREAD

**Issue by javafanboy** [OpenHFT/Chronicle-Map#394]
Do you have any thoughts on introducing a way to include metadata and other extension points in ChronicleMap allowing it to be used as a cache (i.e. I would like to avoid having to redundantly store all the keys one more time for associating them with the required meta data like frequency, most recently get or put request etc.)?

**Comment by JerryShea** [comment]
@javafanboy this sounds like a question for consultancy. Suggest you contact sales@chronicle.software
