### ISSUE TITLE
chronicle-map "3.1.3-alpha" in maven repository can not run on jdk7

### ISSUE THREAD

**Issue by xfeep** [OpenHFT/Chronicle-Map#40]
Was it compiled with jdk 8? 
What 's the jdk requirement of chronicle-map?

When run it on jdk7 it will get an error
```
java.lang.UnsupportedClassVersionError: 
  net/openhft/chronicle/map/ChronicleMapBuilder
 : Unsupported major.minor version 52.0
```

**Comment by RobAustin** [comment]
Please use chronicle map 2.x for java 7. Not chronicle map 3.x

**Comment by xfeep** [comment]
@RobAustin Thanks!
