### ISSUE TITLE
overwrite or time-to-live feature

### ISSUE THREAD

**Issue by MarshalOfficial** [OpenHFT/Chronicle-Map#414]
does ChronicleMap have the ability to overwrite when data is full? or can it has time-to-live, that when the time exceeds that value removes from entries?

```java
this.requestIdLog = ChronicleMap.of(String.class, String.class)
            .name("requestId-clientId-log-map")
            .entries(20_000_000)
            .averageKeySize(1)
            .averageValue(new String())
            .create();
```

**Comment by JerryShea** [comment]
@MarshalOfficial it is better to use stackoverflow for questions. If you would like prioritised answers please explore [support options](https://chronicle.software/support/).
