### ISSUE TITLE
Chronicle-Map UDP Replication feature

### ISSUE THREAD

**Issue by eix128** [OpenHFT/Chronicle-Map#416]
Hi does Chronicle Map has UDP Replication support for Broadcasting ?
TCP is much slower then UDP on broadcasting.
It would be good to add UDP support if not.
There are some reliable udp libraries like Aeron for that.
Also checkout
https://github.com/ChiralBehaviors/udt-java
https://github.com/real-logic/aeron
https://github.com/eleventy7/aeron-cookbook-code

**Comment by JerryShea** [comment]
Hi @eix128, we have support for UDP messaging in our enterprise suite - please contact sales@chronicle.software if you would like to discuss.
