### ISSUE TITLE
Upgrading chronicle-map "2.4.11" -> "3.17.8", lockTimeOut removal

### ISSUE THREAD

**Issue by kkoemets** [OpenHFT/Chronicle-Map#417]
Hi,

I have stumbled upon a small microservice which is using `chronicle-map 2.4.11`, but it does not work when upgrading to `Java 11` from `Java 8`. `chronicle-map 3.17.8`works just fine with exception of a removed method `lockTimeOut(long lockTimeOut, TimeUnit unit)` from `ChronicleMapBuilder`. I am not familiar with the microservice nor with the lovely library of yours, but I have read the following:

```
lockTimeOut(long lockTimeOut, TimeUnit unit)
Configures timeout of locking on segments of hash containers, created by this builder, when performing any queries, as well as bulk operations like iteration.
```
As far as I understand, correct me if I am wrong, it means that `ChronicleMapBuilder` is locked when accessed and there is a timeout to await. Would love to know understand better though.

The default values was 20000L with TimeUnit.MILLISECONDS, however the developer of said microservice configured it to be 1 with TimeUnit.SECONDS. 

My question is whether the API from configuring lock time out was removed completely or there is another way to configure it? I tried searching your git history but unfortunately got overwhelmed.

https://github.com/OpenHFT/Chronicle-Map/blob/dff73d1b3bf2003f1c2a719e6c03844e113f9566/src/main/java/net/openhft/chronicle/hash/impl/BigSegmentHeader.java#L58

Perhaps that is relevant?

Thanks!

**Comment by JerryShea** [comment]
@kkoemets it is best to use stackoverflow for questions.
If you would like a guaranteed response please take a look at https://chronicle.software/support/
