### ISSUE TITLE
The lock file is not always closed

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Map#423]
When `ChronicleMap` construction fails, it can leave a file open. On Windows, it’s then impossible to delete that file because it’s still in use.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Map-3.23ea2](https://github.com/OpenHFT/Chronicle-Map/releases/chronicle-map-3.23ea2), [BOM-2.23ea61](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea61)
