### ISSUE TITLE
BytesMarshallableReaderWriter#read wraps Bytes in Bytes

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Map#446]
We now log.warn if you wrap a Bytes in Bytes - https://github.com/OpenHFT/Chronicle-Bytes/pull/428

`BytesMarshallableReaderWriter#read` does this - should investigate how to not do this

**Comment by JerryShea** [comment]
So does `CompiledReplicatedMapQueryContext.InputKeyBytesData#initInputKeyBytes`

**Comment by hft-team-city** [comment]
Released in [Chronicle-Map-3.23ea4](https://github.com/OpenHFT/Chronicle-Map/releases/chronicle-map-3.23ea4), [BOM-2.23ea121](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea121)
