### ISSUE TITLE
Released 3.23.5 depends on ea/snapshot versions

### ISSUE THREAD

**Issue by rgansevles** [OpenHFT/Chronicle-Map#450]
Hi,

When I update to the latest 3.23.5 version of chronicle-map I get a dependency issue because it depends transitively on a SNAPSHOT version:

_Failed to collect dependencies at net.openhft:chronicle-map:jar:3.23.5 -> net.openhft:affinity:jar:3.23ea1: Failed to read a
rtifact descriptor for net.openhft:affinity:jar:3.23ea1: net.openhft:third-party-bom:pom:3.22.4-SNAPSHOT was not found_

Rob

**Comment by JerryShea** [comment]
https://github.com/OpenHFT/Java-Thread-Affinity/pull/96

**Comment by JerryShea** [comment]
@rgansevles when the next x.23 chronicle-bom is released it will have a dependency on net.openhft:affinity:jar:3.23ea2 which won't have that snapshot dependency. I would advise you to use chronicle-bom to ensure you pick up the right versions. I am going to close this now as the release should be done today
