### ISSUE TITLE
Long runtime compiler initialization may trigger file lock timeout when creating persistent map

### ISSUE THREAD

**Issue by glukos** [OpenHFT/Chronicle-Map#467]
`ChronicleMapBuilder` acquires file write lock and triggers compilation of value class for `VanillaGlobalMutableState`, which may take significant time.
A couple of actions to mitigate this:
1. Always touch `Values.nativeClassFor(VanillaGlobalMutableState.class)` in advance when creating a persistent map (only first invocation can be slow)
2. Add a property for lock timeout - probably won't really be needed after 1), but just in case

**Comment by hft-team-city** [comment]
Released in [Chronicle-Map-3.24ea2](https://github.com/OpenHFT/Chronicle-Map/releases/chronicle-map-3.24ea2), [BOM-2.24ea28](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.24ea28)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Map-3.23.6](https://github.com/OpenHFT/Chronicle-Map/releases/chronicle-map-3.23.6), [BOM-2.23.144](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23.144)
