### ISSUE TITLE
How to create a ChronicleMap<A, ChronicleMap<B, ChronicleMap<C, D>>>?

### ISSUE THREAD

**Issue by dxxvi** [OpenHFT/Chronicle-Map#470]
With Java's Map, I can write something like
```
Map<A, Map<B, Map<C, D>>> map = new ConcurrentHashMap<>();
```
How can I write something like that with ChronicleMap?
```
Map<A, Map<B, Map<C, D>>> map = ChronicleMapBuilder.of(A.class, ???what-should-be-here???).entries(5000).create();
```

**Comment by JerryShea** [comment]
Please use stackoverflow for questions.
Chronicle Map does not support that - if you would like help with your particular use case please explore [support options](https://chronicle.software/support/).
