### ISSUE TITLE
Support CommonMarshallable#usesSelfDescribingMessage()

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Map#480]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Map-3.24ea3](https://github.com/OpenHFT/Chronicle-Map/releases/chronicle-map-3.24ea3), [BOM-2.24ea53](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.24ea53)
