### ISSUE TITLE
Remove internal class in data access documentation

### ISSUE THREAD

**Issue by ginoaugustine** [OpenHFT/Chronicle-Map#494]
https://github.com/OpenHFT/Chronicle-Map/blob/master/docs/CM_Tutorial_DataAccess.adoc refers to HeapBytesStore which is an internal class(package name : net.openhft.chronicle.bytes.internal), can we replace this with BytesStore

**Comment by hft-team-city** [comment]
Released in [Chronicle-Map-3.24ea4](https://github.com/OpenHFT/Chronicle-Map/releases/chronicle-map-3.24ea4), [BOM-2.24ea86](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.24ea86)
