### ISSUE TITLE
The way getFileStores() is used poses problems in a containerized application

### ISSUE THREAD

**Issue by Sax388** [OpenHFT/Chronicle-Map#518]
I don't understand why the following doesn't use `Files.getFileStore(this.file.toPath())`. This retrieves the overlay correctly but the current implementation doesn't, which prevents the creation of a persisted chronicle map.

https://github.com/OpenHFT/Chronicle-Map/blob/79e6e29ebe15a7a72302310738298ac8fabec840/src/main/java/net/openhft/chronicle/hash/impl/VanillaChronicleHash.java#L1100-L1113

**Comment by JerryShea** [comment]
Fixed by #519
