### ISSUE TITLE
chronicle-algorithms 1.1.0 depends on snapshot version of chronicle bom

### ISSUE THREAD

**Issue by kemalerden** [OpenHFT/Chronicle-Map#52]
algorithms a dependency to map depends on chronicle-bom 1.8.11-SNAPSHOT
chronicle-map 3.1.4-alpha depends on 1.8.13

**Comment by RobAustin** [comment]
( thanks for reporting this ) - if it depends on a snapshot version then this is a bug - which we will fix in the next build, sorry about this.

**Comment by kemalerden** [comment]
np at all - thanks for quick response!

**Comment by leventov** [comment]
Please check 3.1.5-alpha release.
