### ISSUE TITLE
chronicle-set doesn't use passed object's hashcode or equals.

### ISSUE THREAD

**Issue by kemalerden** [OpenHFT/Chronicle-Map#53]
ChronicleSet seems to be replacing items based on all fields and ignores the equals and hashcode methods of the passed class. 
     
        class X{
             String a, b, c; //assume getters setters
             boolean equals(Object other) // a==other.a and b==other.b
         }
         ChronicleSet<X> set = ChronicleSetBuilder.of(X).entries(n).create();

Is this a bug or is it deliberately implemented like this? 

Note: I don't want to use chronicle-map in this scenario as I may have to filter based on field a, b or c using java streams. 

              set.stream().filter(x->"a".equals(x.getA()) 
              set.stream().filter(x->"b".equals(x.getB()) etc..

**Comment by leventov** [comment]
In Chronicle Map and Set keys' identity is the sequence of bytes, they are serialized to. Hash code used in data structure is obtained by applying some hash function to the serialised form of the key, and keys are compared by comparing their serialized forms, byte-by-byte.

`equals()` and `hashCode()` of the Key class *never* used.

**Comment by kemalerden** [comment]
Thanks Roman,
I guess this isn't something that you plan to implement (potentially by providing a hashcode/equals functions to the builder or implementing a certain interface etc).
Regards.
Kemal
