### ISSUE TITLE
versions referenced by BOM don't actually exist in maven central

### ISSUE THREAD

**Issue by jbellis** [OpenHFT/Chronicle-Map#537]
Example: https://mvnrepository.com/artifact/net.openhft/chronicle-bom/2.24.99 references core version 2.24.31

which does not exist at https://mvnrepository.com/artifact/net.openhft/chronicle-core

**Comment by JerryShea** [comment]
hi @jbellis - this is by design - see https://github.com/OpenHFT/OpenHFT/blob/ea/docs/Version-Support.adoc#ea-early-access

Only the latest ea versions are deployed to maven central

**Comment by jbellis** [comment]
I see.  Does that actually create material revenue opportunities?  I have to imagine that most people would just build it from source.  So mostly this just increases the adoption difficulty.

**Comment by mdoering** [comment]
Why do you then publish stable BOM releases to Maven Central?
E.g. https://mvnrepository.com/artifact/net.openhft/chronicle-bom/2.26.70 

A bit odd to publish a BOM which has dependencies that are not found in the same repository as the BOM itself.
