### ISSUE TITLE
Maven repository with chronicle-map-3.25.8

### ISSUE THREAD

**Issue by shestkov** [OpenHFT/Chronicle-Map#549]
hi chronicle team,

I see that [chronicle-map-3.25.8](https://github.com/OpenHFT/Chronicle-Map/releases/tag/chronicle-map-3.25.8) vas released. But I cant find it in maven central. Only "ea" releases are there. 

Is that something wrong with you release system or it published to some other repository?

**Comment by JerryShea** [comment]
hi @shestkov please have a look at https://github.com/OpenHFT/OpenHFT/blob/ea/docs/Version-Support.adoc#ea-early-access
