### ISSUE TITLE
Error 401 while downloading dependencies

### ISSUE THREAD

**Issue by Flole998** [OpenHFT/Chronicle-Map#550]
I am trying to include this library in a project, but upon adding it to my pom.xml as described in the download documentation I receive this error:

```
[ERROR] Failed to read artifact descriptor for net.openhft:chronicle-analytics:jar:2.26ea0
[ERROR]         Caused by: The following artifacts could not be resolved: net.openhft:third-party-bom:pom:3.26.0-SNAPSHOT (absent): Could not transfer artifact net.openhft:third-party-bom:pom:3.26.0-SNAPSHOT from/to chronicle-enterprise-snapshots (https://nexus.chronicle.software/content/repositories/snapshots): status code: 401, reason phrase: Unauthorized (401)
```

I also tried using the other method with the dependency manager, but that leads to the import being unresolvable.

**Comment by tgd** [comment]
Hi @Flole998 - we have been able to reproduce this and are looking into a resolution. Will come back with some more information soon.

**Comment by ibalashov** [comment]
@tgd We're also seeing this. Is there a workaround? Maybe we could use some non-snapshot version?

**Comment by tgd** [comment]
Hi @ibalashov this should be fixed in the latest dependency versions. Are you still experiencing an issue?

**Comment by ibalashov** [comment]
@tgd Yes, fixed indeed. I didn't notice that we used not the latest version. Thanks!

**Comment by tgd** [comment]
Excellent thank you @ibalashov for the confirmation - I'll close this ticket now
