### ISSUE TITLE
Add option for putIfAbsentUsingValue to builder

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Map#552]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Map-3.23.8](https://github.com/OpenHFT/Chronicle-Map/releases/chronicle-map-3.23.8), [BOM-2.23.225](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23.225)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Map-3.26ea4](https://github.com/OpenHFT/Chronicle-Map/releases/chronicle-map-3.26ea4), [BOM-2.26ea40](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.26ea40)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Map-3.25.9](https://github.com/OpenHFT/Chronicle-Map/releases/chronicle-map-3.25.9), [BOM-2.25.84](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.25.84)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Map-3.25.9](https://github.com/OpenHFT/Chronicle-Map/releases/chronicle-map-3.25.9), [BOM-2.25.85](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.25.85)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Map-3.24.6](https://github.com/OpenHFT/Chronicle-Map/releases/chronicle-map-3.24.6), [BOM-2.24.142](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.24.142)
