### ISSUE TITLE
concurrent update replication map  throw IllegalStateException

### ISSUE THREAD

**Issue by zhyhang** [OpenHFT/Chronicle-Map#59]
When concurrent update a repliation map, often throw IllegalStateException.
I checked the net.openhft.chronicle.map.ReplicatedChronicleMap.update() method codes. **Map hold a timestamp and then call segment.update() which method following acquire a writelock . When multi-threads holding different timestamp wait the lock, possiblly, the old timestamp thread entered lately, because newer timestamp thread has updated the enty. An IllegalStateException thrown?**

**Comment by leventov** [comment]
Indeed. As a workaround, you could try to perform your updates in `acquireUsingLocked()`, which acquires write lock before obtaining current timestamp for replicated entry. Or, move to Chronicle Map 3, which doesn't have problem.

**Comment by zhyhang** [comment]
Thanks. When will the 3.x GA release?

**Comment by leventov** [comment]
Hard question, I believe this year, Beta release sooner
