### ISSUE TITLE
Chronicle-Map (3.2.0-beta) maxBloatFactor issue

### ISSUE THREAD

**Issue by maxime-leur** [OpenHFT/Chronicle-Map#60]
Hi,

I have downloaded and tested Chronicle-Map (3.2.0) with maxBloatFactor and I have issues on this feature.

I use Chronicle-Map 2.x but I am interested by the possibility to go beyond the entries defined at startup (e.g https://github.com/OpenHFT/Chronicle-Map#difference-between-chronicle-map-2-and-3)

It works on put, but failed on some get and on iteration.
Here is the code:

```java
int entries = 200;
int maxBloatFactor = 10;
int loop = 1000;

ChronicleMapBuilder<String,String> builder = ChronicleMapBuilder.of(String.class,String.class).
			entries(entries).averageKeySize(12).averageValueSize(12).maxBloatFactor(maxBloatFactor);		
ChronicleMap<String, String> map = builder.create();

System.out.println("begin test "+map.size());
for (int i=0;i<loop;i++)
{
	map.put("key"+i, "value"+i);
}		
System.out.println("map size "+map.size());

int failedGet = 0;
for (int i=0;i<loop;i++)
{
	String value = map.get("key"+i);
	if (value == null)
	{
		failedGet++;
	}
}		
System.out.println("failedGet "+failedGet);
System.out.println("map "+map);
map.close();	
```

The result is:
```java
begin test 0
16:35:40.581 [main] DEBUG n.o.c.hash.impl.VanillaChronicleHash - Allocate tier for segment # 0, tier 1
16:35:40.626 [main] DEBUG n.o.c.hash.impl.VanillaChronicleHash - Allocate tier for segment # 0, tier 2
map size 1000
failedGet 172
Exception in thread "main" java.lang.IllegalStateException: We iterated all tiers without interruption, but according to size counter there should be 172 more entries. Size diverged?
	at net.openhft.chronicle.map.impl.CompiledMapIterationContext.forEachSegmentEntryWhile(CompiledMapIterationContext.java:2833)
	at net.openhft.chronicle.map.AbstractChronicleMap.forEachEntryWhile(AbstractChronicleMap.java:248)
	at net.openhft.chronicle.map.AbstractChronicleMap.forEachEntry(AbstractChronicleMap.java:237)
	at net.openhft.chronicle.map.AbstractChronicleMap.forEach(AbstractChronicleMap.java:71)
	at net.openhft.chronicle.map.AbstractChronicleMap.mapToString(AbstractChronicleMap.java:219)
	at net.openhft.chronicle.map.VanillaChronicleMap.toString(VanillaChronicleMap.java:253)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at DefaultTest.main(DefaultTest.java:44)
```

Regards,

Maxime

**Comment by leventov** [comment]
@maxime-leur see the added test, it passes on my laptop (Windows) and our Linux CI server.

**Comment by maxime-leur** [comment]
Hi,

This test failed on windows 64 bits with JDK 1.8.0_60.
It is maybe due to my librairies version:
 -  lib/chronicle-bytes-1.1.8.jar,
 -  lib/chronicle-core-1.1.6.jar,
 -  lib/chronicle-threads-1.1.3.jar,
 -  lib/chronicle-values-1.0.2-alpha.jar,
 -  lib/chronicle-wire-1.1.5.jar,
 -  lib/compiler-2.2.1.jar,
 -  lib/jettison-1.3.6.jar,
 -  lib/jna-4.1.0.jar,
 -  lib/jna-platform-4.1.0.jar,
 -  lib/kxml2-2.3.0.jar,
 -  lib/xstream-1.4.7.jar,
 -  lib/chronicle-map-3.2.0-beta.jar,
 -  lib/chronicle-algorithms-1.1.3.jar

Regards,

Maxime

**Comment by leventov** [comment]
It shouldn't be because of the libs, because you have the up-to-date versions.

You could try to create a persisted map (`createPersistedTo("mymap")` instead of `create()` and if it still fails, send me the persistence file.

Or, at least please send the keys which were not found.

**Comment by leventov** [comment]
Hi @maxime-leur I hope this bug is fixed now with commit a0c982374dde93587925547996c57f2dcd14a7e4
However I don't see how this bug was non-deterministic -- passing in our environments and failing in yours, with exactly the same configuration.

**Comment by leventov** [comment]
You could try to use the latest `3.2.1-beta-SNAPSHOT` version to check, as described [here](https://github.com/OpenHFT/Chronicle-Map#maven-artifact-download)

**Comment by maxime-leur** [comment]
Hi,

I have download the snapshot version "chronicle-map-3.2.1-beta-20151128.225647-4.jar" but I have the same issues (map.toString() failed).
Even with a persisted  map.

Here is the persisted file:
[test.txt](https://github.com/OpenHFT/Chronicle-Map/files/47560/test.txt)

Thanks for your help.
Regards,

Maxime

**Comment by vaibhaviit2002** [comment]
I am facing same issue. When I play with entries method (while writing data), I get different results and when I increased that number, problem was solved. But I increased it to a number much higher than actual no. of elements I am going to insert.
ChronicleMapBuilder<CharSequence, SymbolInfo> cityPostalCodesMapBuilder = ChronicleMapBuilder.of(CharSequence.class, SymbolInfo.class).averageKey("key1")
				.entries((long) (5000000 * 9))

I was using .entries((long) (5000000 * 7) and I got error Exception in thread "main" java.lang.IllegalStateException: We iterated all tiers without interruption, but according to size counter there should be 2more entries. Size diverged?

I changed it to .entries((long) (5000000 * 8)
Exception in thread "main" java.lang.IllegalStateException: We iterated all tiers without interruption, but according to size counter there should be 1more entries. Size diverged?

Increasing it to .entries((long) (5000000 * 9) solved the issue. But I think this is a bug.
Please fix this.

I am using Win7, Java8 64 bit and chronicle-map-3.2.0-beta.jar

**Comment by leventov** [comment]
@vaibhaviit2002 how many entries do you actually have, in this test?

**Comment by vaibhaviit2002** [comment]
@leventov I have 5000000 entries of my custom class which has 3 string and 2 double fields. Quick question: in this case is it correct to provide entries as 5000000 or 5000000*5 (5 fields)?

**Comment by leventov** [comment]
@vaibhaviit2002 no, you should configure just `entries(5000000)`, if it isn't enough, you should have configured `averageKey()` or `averageValue()` (or `averageKeySize`/`averageValueSize`) wrong. They should reflect the average number of bytes, taken by instances when serialized, not "average" in any other sense (e. g. average values in integer fields).

Returning to your first question, there was one bug which used to lead to "Size diverged" error message, that is already fixed (you could try [3.2.1-beta-SNAPSHOT](https://github.com/OpenHFT/Chronicle-Map#maven-snapshot-download) to check), but @maxime-leur reports the issue is still here, that I'm investigating now.

**Comment by leventov** [comment]
@maxime-leur apparently that "non-determinism" was just that you run the test without `-ea`, while we run with assertions enabled in all environments. Fixed in the latest SNAPSHOT.

**Comment by maxime-leur** [comment]
Hi,

I confirm that it is fixed with lastest snapshot.
Many thanks.

Regards,
Maxime
