### ISSUE TITLE
net.openhft.chronicle.bytes.UTFDataFormatRuntimeException: malformed input around byte 23 was 58 36

### ISSUE THREAD

**Issue by daffy1981** [OpenHFT/Chronicle-Map#62]
UTFDataFormatRuntimeException is being generated when Chronicle Map sink receives entry which key is a long String.
I also tried using byte[], that resulted in malformed value (though it didn't throw an exception ) .

I created two classes for demonstration, a "server" that creates a map, and then a "client" that is connecting, receiving updates and failing to read map, with "malformed input..." exception.

* daffy1981/CHMap@52a5fc43f27c7cf75cfaf64178ba6461157fd372

This started failing since 3.2.0-beta version (I also checked, 3.3.0-beta, and current 3.3.4-SNAPSHOT versions). Last versions that works is 3.1.5-alpha.

**Comment by leventov** [comment]
@daffy1981 this bug should be fixed in the latest `3.4.0-beta-SNAPSHOT`.
