### ISSUE TITLE
Tcp bootstrapping can not replicate whole remote map?

### ISSUE THREAD

**Issue by zhyhang** [OpenHFT/Chronicle-Map#74]
version: chronicle-map 2.x

Create two chronicle-map that replicating through tcp. Start first, write 30million entries (String,LongValue). Start second on remote server, bootstrapping doing, but can not get the whole map entries? Wait a long time about 1 hour, also did not complete bootstrapping. Network is ok, ttl about 0.3ms between servers. We also see that more smaller entries, more better.

code:

``` java
        File f = new File(persistFile);
        f.deleteOnExit();
        TcpTransportAndNetworkConfig tcpConfig = TcpTransportAndNetworkConfig
                .of(port, new InetSocketAddress(host, port)).heartBeatInterval(1L, TimeUnit.SECONDS)
                .autoReconnectedUponDroppedConnection(true);
        ChronicleMapBuilder<String, LongValue> mapBuilder = ChronicleMapBuilder.of(String.class, LongValue.class)
                .entries(30000000L).replication(identifier, tcpConfig);
        map = mapBuilder.createPersistedTo(f);
        ...

        putBulkEntries()...// first server put about 30million entries, second server only boot and wait replication.


```

Thanks.

**Comment by peter-lawrey** [comment]
Which version of chronicle map are you using as there was an issue with
older version.

**Comment by zhyhang** [comment]
2.4.13

**Comment by zhyhang** [comment]
Hi peter-lawrey,
I found this issue possiblly due to heartBeatInterval. In my code, the heartBeatInterval is 1 second. On bootstrapping stage, large entries need to replicate, tcp replicator thread while doing the replication, while doing handshake and dirty entries. It's too busy to do anything. In my server is always cosume 100% cpu.

**Comment by RobAustin** [comment]
closing as we no longer provide support to chronicle map v2
