### ISSUE TITLE
Windows: cannot write a map

### ISSUE THREAD

**Issue by krolen** [OpenHFT/Chronicle-Map#8]
It might be a windows-only issue and might be JDK related only (from what I've googled so far).

Basically this code does not work:

      Paths.get(System.getProperty("java.io.tmpdir"), "SimpleTest")
      int entries = 30_000_000;
      ChronicleMapBuilder<Long, SimpleBean> builder = ChronicleMapBuilder.of(Long.class, SimpleBean.class).valueSize(56).entries(entries);
      ChronicleMap<Long, SimpleBean> map = builder.createPersistedTo(file.toFile());

The same code works well with `entries = 10_000_000` 
This guy: https://community.oracle.com/thread/3628455?start=0&tstart=0 has mentioned that this is most likely because of GC.

I do understand that most probably it is a windows related stuff but it makes me feel a bit uncomfortable. 
Does it make sense to mention that Chronicle does not work on windows for a big data?

Exception:

Connected to the target VM, address: '127.0.0.1:57396', transport: 'socket'
A fatal error has been detected by the Java Runtime Environment:
 EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x0000000002cfa3e0, pid=1444, tid=3620
JRE version: Java(TM) SE Runtime Environment (8.0_25-b18) (build 1.8.0_25-b18)
Java VM: Java HotSpot(TM) 64-Bit Server VM (25.25-b02 mixed mode windows-amd64 compressed oops)
Problematic frame:
J 422 C1 net.openhft.lang.io.NativeBytes.load()Lnet/openhft/lang/io/Bytes; (39 bytes) @ 0x0000000002cfa3e0 [0x0000000002cfa2c0+0x120]
 Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
 An error report file with more information is saved as:
 C:\Projects\HftTests\hs_err_pid1444.log

 If you would like to submit a bug report, please visit:
   http://bugreport.sun.com/bugreport/crash.jsp

File:
https://github.com/krolen/hfttests/blob/master/hs_err_pid1444.log

**Comment by javalama** [comment]
Chronicle-Map (and any other Java library) depending on memory mapped files is basically  a no-go on Windows. The amount of problems pile up (even the JVM struggles with properly closing mapped files)

The chronicle family is great under OSX and Linux, but I wouldn't even consider it for Windows. Not sure what the remedy is.

**Comment by peter-lawrey** [comment]
We don't use the JVM's unmapping mechanism as it's not deterministic and we
don't want to assume the GC will be called (ever).

For Chronicle Queue, we unmap deterministically and for Chronicle Map we
only unmap when the map is closed.

That said I would rather not use using Windows for production.  Most of our
client prefer to use Linux (usually RHEL or Centos)
