### ISSUE TITLE
3.9.0-SNAPSHOT has broken dependencies

### ISSUE THREAD

**Issue by IceMan81** [OpenHFT/Chronicle-Map#83]
The pom in the master branch is referencing 
```
            <dependency>
                <groupId>net.openhft</groupId>
                <artifactId>chronicle-bom</artifactId>
                <type>pom</type>
                <version>1.12.14-SNAPSHOT</version>
                <scope>import</scope>
            </dependency>

```
which is not published to the snapshot repository.

**Comment by peter-lawrey** [comment]
Thank you for letting us know.    We have added a check which should
prevent a SNAPSHOT BOM in the release.

This will need to be re-released.  We have a release of bom 1.12.18 this
evening.  I will make sure this is in the next bom.

**Comment by leventov** [comment]
As of 3.9.0, this shouldn't be an issue anymore because chronicle-bom dependency updated to a released version.
