### ISSUE TITLE
Can not close a file-based Chronicle Map.

### ISSUE THREAD

**Issue by MartinanderssonDotcom** [OpenHFT/Chronicle-Map#96]
It is possible - maybe even likely - that I know not what I am talking about.

However, I can not close a file-based (persisted) Chronicle Map without having an `IllegalStateException` thrown. After this exception, the file is still in used, rendering it useless to other processes that want to write or delete it.

Here's my "proof":

```
ChronicleMapBuilder<Integer, Integer> builder
        = ChronicleMapBuilder.of(Integer.class, Integer.class)
                .constantKeySizeBySample(1)
                .constantValueSizeBySample(1)
                .entries(1)
                .putReturnsNull(true)
                .removeReturnsNull(true)
                // This is the default, but who knows about the future:
                .checksumEntries(true);

Path file = Paths.get("file.dat");

ChronicleMap<Integer, Integer> created
        = builder.createPersistedTo(file.toFile());

created.put(1, 2);

// true
System.out.println("created.isOpen(): " + created.isOpen());

created.close();

// false
System.out.println("created.isOpen(): " + created.isOpen());

// Rename file to newfile; works because previous close released the file.
Path newfile = file.resolveSibling("newfile.dat");
Files.move(file, newfile);

ChronicleMap<Integer, Integer> opened
        = builder.recoverPersistedTo(newfile.toFile(), true);

// 2
System.out.println("opened.get(1): " + opened.get(1));

try {
    opened.close();
    throw new RuntimeException("Forget everything. There's no bug.");
}
catch (IllegalStateException e) {
    // "Attempt to close a Chronicle Hash in the context of not yet finished query or iteration"
    System.out.println("e.getMessage(): " + e.getMessage());
}

// false
System.out.println("opened.isOpen(): " + opened.isOpen());

try {
    Files.move(newfile, file);
    throw new RuntimeException("Forget everything. There's no bug.");
}
catch (IOException e) {
    // "newfile.dat -> file.dat: The process cannot access the file because it is being used by another process."
    System.out.println("e.getMessage(): " + e.getMessage());
}
```

I have tried a plethora of different hacks and builder configurations (including new builder instances) and what else. I simply can't find a way to close a file-based Chronicle Map! Maybe same problem exists for in-memory maps, I don't know.

Most notably, I have tried various thread sleeps here and there without any success.

Please note that this "app" is single-threaded. If we close the map using a new thread, Chronicle Map will internally "wait" for a lock of some kind, and after about 2 minutes, he will crash with another exception whose message speak of a "deadlock".

All in all, this do sound like a bug to me.

I am using Chronicle Map `3.10.0`. But if I remember correctly, I have seen this on `3.8.0` as well.

**Comment by leventov** [comment]
Thank you very much for preparing an easily reproducible test.

Indeed this was a bug. Now fixed, will be available in 3.10.1 soon.

An easy workaround would be just not to use `recoveryPersistedTo()`, use `createPersistedTo()` instead. And it's not just a workaround, actually it is a proper way to open a map in your situation. See this: https://github.com/OpenHFT/Chronicle-Map/issues/90#issuecomment-237292926 for more information and reasoning.

**Comment by leventov** [comment]
3.10.1 is released now.

**Comment by MartinanderssonDotcom** [comment]
Thank you! That was fast, wow =)

I understand that the "recovery" is only for "abnormal", "exceptional" cases. But I'd rather open through recovery than "risk" having corrupt data, no matter how slow recovery may be?

My maps are only opened (recovered) by one process and one thread. Once a map is opened, it is released to the app and may be concurrently accessed (only reads, no writes).

So far, I have used hundreds of thousands of maps (and files). It is "quite common" that Chronicle Map remove entries during recovery (I write the count of entries to a separate file the first time I create the map), not that I have any statistics to present but I see it "all the time". Please note that statistically this might not happened often at all, but I notice it a lot because I use so many maps.

I can not explain it actually. I don't think my app has ever crashed during a map file write. What the app does is that it downloads tons of stuff, once this stuff is downloaded, it put it in a new file-based Chronicle Map. The Chronicle Map reference remains open for the rest of the program execution. Next time the app runs, he's going to open the Chronicle Map file, and redownload/rewrite the file only if the data "expired" or if the recovery made entries go missing.

Since I only write once to the file and this has never crashed, I can't figure out why entries go missing for me =) I have run a few checks on my disk and it appears to be just fine.

Anyways, bottom line is that since I do see entries go missing from time to time, I dare not _not_ do "recovery" even though it might be computationally expensive. Since only one process and one thread do the recovery, I don't see that I run a risk of getting into all those danger zones the tutorial and other docs has described?

**Comment by leventov** [comment]
Yes, indeed this seems strange. Maybe you restart your machine, before the OS complete flushing memory mapped files in background?

**Comment by MartinanderssonDotcom** [comment]
No. But it appears that the same data is the data being corrupt all the time despite being "re-downloaded and re-persisted". I can't directly see how my domain models are to be blamed for it, on the other hand even less do I know about the internals of Chronicle Map =) I will have to investigate this further. If I find or have reason to suspect Chronicle Map is at fault, then I shall open a new ticket =)

**Comment by leventov** [comment]
Recovery procedure does some SLF4J logging on ERROR level, when it encounters something it thinks is corrupt. It would be helpful if you could turn it on and see what it logs.
