### ISSUE TITLE
SIGSEGV when reading data

### ISSUE THREAD

**Issue by dankristensen** [OpenHFT/Chronicle-Map#97]
C  [libc.so.6+0x1388cb]
j  sun.misc.Unsafe.copyMemory(Ljava/lang/Object;JLjava/lang/Object;JJ)V+0
j  net.openhft.lang.io.NativeBytes.read([BII)I+67
j  net.openhft.lang.io.AbstractBytes.read([B)I+5
j  com.cofman.xmlv2.archive.DataReaderExcerpt.readDataAtIndex(J)Ljava/lang/Object;+132

Is what i get when reading data from a ChronicleMap.

I have attached the log file.

[hs_err_pid6289.zip](https://github.com/OpenHFT/Chronicle-Map/files/437197/hs_err_pid6289.zip)

**Comment by dankristensen** [comment]
I am running on latest java version:

java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)


On:
uname -a
Linux t-generate01 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2+deb8u3 (2016-07-02) x86_64 GNU/Linux

**Comment by leventov** [comment]
Chronicle Map 2 is not not supported for free now. What are the limitations that doesn't allow you to switch to Chronicle Map 3?

**Comment by RobAustin** [comment]
thanks for the attachment, 

`Stack: [0x00007f5f5e521000,0x00007f5f5e622000],  sp=0x00007f5f5e6200f8,  free space=1020k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libc.so.6+0x1388cb]
j  sun.misc.Unsafe.copyMemory(Ljava/lang/Object;JLjava/lang/Object;JJ)V+0
j  net.openhft.lang.io.NativeBytes.read([BII)I+67
j  net.openhft.lang.io.AbstractBytes.read([B)I+5
j  com.cofman.xmlv2.archive.DataReaderExcerpt.readDataAtIndex(J)Ljava/lang/Object;+132
j  com.cofman.xmlv2.archive.impl.ChronicleArchive.getLatestAt(Ljava/lang/String;J)Ljava/lang/Object;+114
j  com.cofman.xmlv2.archive.impl.ChronicleArchive.getLatestEntryAt(Ljava/lang/String;J)Lcom/cofman/xmlv2/archive/ArchiveEntryWrapper;+17
j  com.cofman.xmlv2.archive.impl.ChronicleArchive.getLatestEntry(Ljava/lang/String;)Lcom/cofman/xmlv2/archive/ArchiveEntryWrapper;+5
j  com.cofman.xmlv2.archive.impl.ChronicleArchive.getLatestEntry(Ljava/lang/Object;)Lcom/cofman/xmlv2/archive/ArchiveEntryWrapper;+5
j  com.cofman.xmlv2.generator.helpers.AvailabilityHelper.findPreviouslyGeneratedFirstMonth(Lcom/cofman/xmlv2/archive/ArchiveReader;Ljava/lang/String;Ljavax/xml/bind/Unmarshaller;)Lcom/cofman/xmlv2/Month;+19
j  com.cofman.interhome.InterhomeXmlv2Generator.createConversionData(Ljava/lang/String;)Lcom/cofman/xmlv2/generator/ConversionData;+89
j  com.cofman.xmlv2.generator.AbstractXmlV2Generator.generateProperties(Ljava/util/Set;J)Z+80
j  com.cofman.xmlv2.generator.AbstractXmlV2Generator.generate()Z+208
j  com.cofman.interhome.InterhomeXmlv2Generator.generate()Z+155
j  com.cofman.interhome.InterhomeXmlv2Generator.main([Ljava/lang/String;)V+12
v  ~StubRoutines::call_stub
V  [libjvm.so+0x68f6b6]  JavaCalls::call_helper(JavaValue*, methodHandle*, JavaCallArguments*, Thread*)+0x1056
V  [libjvm.so+0x6d0d42]  jni_invoke_static(JNIEnv_*, JavaValue*, _jobject*, JNICallType, _jmethodID*, JNI_ArgumentPusher*, Thread*)+0x362
V  [libjvm.so+0x6ed5aa]  jni_CallStaticVoidMethod+0x17a
C  [libjli.so+0x7bdf]  JavaMain+0x81f
C  [libpthread.so.0+0x80a4]  start_thread+0xc4

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  sun.misc.Unsafe.copyMemory(Ljava/lang/Object;JLjava/lang/Object;JJ)V+0
j  net.openhft.lang.io.NativeBytes.read([BII)I+67
j  net.openhft.lang.io.AbstractBytes.read([B)I+5
j  com.cofman.xmlv2.archive.DataReaderExcerpt.readDataAtIndex(J)Ljava/lang/Object;+132
j  com.cofman.xmlv2.archive.impl.ChronicleArchive.getLatestAt(Ljava/lang/String;J)Ljava/lang/Object;+114
j  com.cofman.xmlv2.archive.impl.ChronicleArchive.getLatestEntryAt(Ljava/lang/String;J)Lcom/cofman/xmlv2/archive/ArchiveEntryWrapper;+17
j  com.cofman.xmlv2.archive.impl.ChronicleArchive.getLatestEntry(Ljava/lang/String;)Lcom/cofman/xmlv2/archive/ArchiveEntryWrapper;+5
j  com.cofman.xmlv2.archive.impl.ChronicleArchive.getLatestEntry(Ljava/lang/Object;)Lcom/cofman/xmlv2/archive/ArchiveEntryWrapper;+5
j  com.cofman.xmlv2.generator.helpers.AvailabilityHelper.findPreviouslyGeneratedFirstMonth(Lcom/cofman/xmlv2/archive/ArchiveReader;Ljava/lang/String;Ljavax/xml/bind/Unmarshaller;)Lcom/cofman/xmlv2/Month;+19
j  com.cofman.interhome.InterhomeXmlv2Generator.createConversionData(Ljava/lang/String;)Lcom/cofman/xmlv2/generator/ConversionData;+89
j  com.cofman.xmlv2.generator.AbstractXmlV2Generator.generateProperties(Ljava/util/Set;J)Z+80
j  com.cofman.xmlv2.generator.AbstractXmlV2Generator.generate()Z+208
j  com.cofman.interhome.InterhomeXmlv2Generator.generate()Z+155
j  com.cofman.interhome.InterhomeXmlv2Generator.main([Ljava/lang/String;)V+12
v  ~StubRoutines::call_stub`

**Comment by RobAustin** [comment]
which version of chronicle map are you using ?

**Comment by RobAustin** [comment]
This looks like its not a Chronicle Map issue, from the stack trace it looks like you are making a call to

```
 net.openhft.lang.io.AbstractBytes.read([B)I+5
```

this is reading from the wrong place in memory. This JVM crash can occur it you read memory that is outside of that controlled by the JVM. Maybe the `positionAddr` was wrong. Or the byte[] that you are reading into is too large, with the information I have here its hard to say.  However when using AbstractBytes as you are, it should not be possible to set an incorrect `positionAddr` or read too many bytes.

but from the stacks above, it looks like the JVM is crashing here

```
    @Override
    public int read(@NotNull byte[] bytes, int off, int len) {
        if (len < 0 || off < 0 || off + len > bytes.length)
            throw new IllegalArgumentException();
        long left = remaining();
        if (left <= 0) return -1;
        int len2 = (int) Math.min(len, left);
        UNSAFE.copyMemory(null, positionAddr, bytes, BYTES_OFFSET + off, len2);
        addPosition(len2);
        return len2;
    }
```

 
**net.openhft.lang.io.AbstractBytes is single threaded, so make sure that you are not calling the same instance of AbstractBytes with multiple threads.**

**Comment by dankristensen** [comment]
Hi Austin

Thanx for your reply. I have identified the problem. The problem was how i instantiated my second instance of a ChronicleQueue. I did not use the correct dataBlockSize, which resulted in the above problem. 

Will close the case. Thanx for taking time to look at this ;-)
