### ISSUE TITLE
Iterating over ChronicleMap results in Exception

### ISSUE THREAD

**Issue by leventov** [OpenHFT/Chronicle-Map#99]
This issue is raised here: http://stackoverflow.com/questions/39546013/iterating-over-chroniclemap-results-in-exception

I am using v3.10.1 of Chronicle Map. In my map, I have approximately 77K entries. I am trying to iterate through this map using entrySet() method. It doesn't iterate successfully and in between throws Chronicle specific exception. Here are the logs produced from Chronicle Map

```
016-09-17 06:39:15 [ERROR] n.o.c.m.i.CompiledMapIterationContext - Contexts locked on this segment:
net.openhft.chronicle.map.impl.CompiledMapIterationContext@205cd34b: used, segment 62, local state: UNLOCKED, read lock count: 0, update lock count: 0, write lock count: 0
Current thread contexts:
net.openhft.chronicle.map.impl.CompiledMapIterationContext@205cd34b: used, segment 62, local state: UNLOCKED, read lock count: 0, update lock count: 0, write lock count: 0
```

and Exception:

```
2016-09-17 06:39:15 [ERROR] akka.dispatch.TaskInvocation - Failed to acquire the lock in 60 seconds.
    Possible reasons:
     - The lock was not released by the previous holder. If you use contexts API,
     for example map.queryContext(key), in a try-with-resources block.
     - This Chronicle Map (or Set) instance is persisted to disk, and the previous
     process (or one of parallel accessing processes) has crashed while holding
     this lock. In this case you should use ChronicleMapBuilder.recoverPersistedTo() procedure
     to access the Chronicle Map instance.
     - A concurrent thread or process, currently holding this lock, spends
     unexpectedly long time (more than 60 seconds) in
     the context (try-with-resource block) or one of overridden interceptor
     methods (or MapMethods, or MapEntryOperations, or MapRemoteOperations)
     while performing an ordinary Map operation or replication. You should either
     redesign your logic to spend less time in critical sections (recommended) or
     acquire this lock with tryLock(time, timeUnit) method call, with sufficient
     time specified.
     - Segment(s) in your Chronicle Map are very large, and iteration over them
     takes more than 60 seconds. In this case you should
     acquire this lock with tryLock(time, timeUnit) method call, with longer
     timeout specified.
     - This is a dead lock. If you perform multi-key queries, ensure you acquire
     segment locks in the order (ascending by segmentIndex()), you can find
     an example here: https://github.com/OpenHFT/Chronicle-Map#multi-key-queries

    java.lang.RuntimeException: Failed to acquire the lock in 60 seconds.
    Possible reasons:
     - The lock was not released by the previous holder. If you use contexts API,
     for example map.queryContext(key), in a try-with-resources block.
     - This Chronicle Map (or Set) instance is persisted to disk, and the previous
     process (or one of parallel accessing processes) has crashed while holding
     this lock. In this case you should use ChronicleMapBuilder.recoverPersistedTo() procedure
     to access the Chronicle Map instance.
     - A concurrent thread or process, currently holding this lock, spends
     unexpectedly long time (more than 60 seconds) in
     the context (try-with-resource block) or one of overridden interceptor
     methods (or MapMethods, or MapEntryOperations, or MapRemoteOperations)
     while performing an ordinary Map operation or replication. You should either
     redesign your logic to spend less time in critical sections (recommended) or
     acquire this lock with tryLock(time, timeUnit) method call, with sufficient
     time specified.
     - Segment(s) in your Chronicle Map are very large, and iteration over them
     takes more than 60 seconds. In this case you should
     acquire this lock with tryLock(time, timeUnit) method call, with longer
     timeout specified.
     - This is a dead lock. If you perform multi-key queries, ensure you acquire
     segment locks in the order (ascending by segmentIndex()), you can find
     an example here: https://github.com/OpenHFT/Chronicle-Map#multi-key-queries

        at net.openhft.chronicle.hash.impl.BigSegmentHeader.deadLock(BigSegmentHeader.java:59)
        at net.openhft.chronicle.hash.impl.BigSegmentHeader.updateLock(BigSegmentHeader.java:231)
        at net.openhft.chronicle.map.impl.CompiledMapIterationContext$UpdateLock.lock(CompiledMapIterationContext.java:768)
        at net.openhft.chronicle.map.impl.CompiledMapIterationContext.forEachSegmentEntryWhile(CompiledMapIterationContext.java:3810)
        at net.openhft.chronicle.map.impl.CompiledMapIterationContext.forEachSegmentEntry(CompiledMapIterationContext.java:3816)
        at net.openhft.chronicle.map.ChronicleMapIterator.fillEntryBuffer(ChronicleMapIterator.java:61)
        at net.openhft.chronicle.map.ChronicleMapIterator.hasNext(ChronicleMapIterator.java:77)
        at java.lang.Iterable.forEach(Iterable.java:74)
```

It is a single-threaded and persistent map.

**Comment by chauhraj** [comment]
It was able to read around 1200 entries. I found this by adding debug statements. It gets locked when it invokes the method `fillEntryBuffer` the second time.

**Comment by leventov** [comment]
@chauhraj it seems that some segments in your Map are locked, because process(es) holding them were killed. You could try to recover using `ChronicleMapBuilder.recoverPersistedTo()` and then try to iterate again.

**Comment by chauhraj** [comment]
@leventov I am curious to know how it works. It seems like it is not using JVM locks but kernel locks. If it is using JVM locks then is it persisting that lock information too. Because, as soon as a process is killed, if it isn't system resource like kernel locks, then those resources should also vanish with the process.

It seems that I can use either `ChronicleMapBuilder.recoverPersistedTo()` or `ChronicleMapBuilder.createPersistedTo()` in my main application. In cases like mine, what is the design pattern that you guys recommend? I am having this issue in production and I cannot change the code and re-deploy and then change code again to use createPersistedTo and re-deploy.

Or 
are you recommending to have another utility that uses `ChronicleMapBuilder.recoverPersistedTo()` to recover the data and exit cleanly?

**Comment by leventov** [comment]
Chronicle Map uses neither "JVM native" (aka intrinsic) nor kernel locks. [It implements locks themselves, using CAS operations with shared mapped memory](https://github.com/OpenHFT/Chronicle-Map/blob/master/spec/2-design-overview.md#lock-implementation), which allows them to be fast (unlike kernel locks, at least when called from Java) and inter-process (unlike JVM intrinsic locks).

Unfortunately this comes with downsides: those locks are not vanished by neither JVM nor kernel, when the acessing process is killed, or crashed.

>  It seems that I can use either ChronicleMapBuilder.recoverPersistedTo() or ChronicleMapBuilder.createPersistedTo() in my main application. In cases like mine, what is the design pattern that you guys recommend? I am having this issue in production and I cannot change the code and re-deploy and then change code again to use createPersistedTo and re-deploy.

> Or 
are you recommending to have another utility that uses ChronicleMapBuilder.recoverPersistedTo() to recover the data and exit cleanly?

I do *not* recommend to always open Chronicle Maps using `createOrRecoverPersistedTo()` method, [as I explained here](https://github.com/OpenHFT/Chronicle-Map/issues/90#issuecomment-237292926). If you have to kill a Chronicle Map accessor process in production, I recommend to

1) Ensure all other concurrent processes accessing Chronicle Map are shutdown as well, because [recovery needs it](http://stackoverflow.com/a/38614626/648955).
2) Run a special utility, which exclusively calls `ChronicleMap.of(keyClass, valueClass).recoverPersistedTo()` on the needed file
3) Start production processes again, which open a map using `createPersistedTo()`.

I understand that this is not super convenient, unfortunately Chronicle Map is not very manageable ATM, certain improvements are possible.

**Comment by minborg** [comment]
Closing as per the workaround provided above.
